/-
Copyright (c) 2026 Pietro Monticone. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aristotle (Harmonic), Pietro Monticone, Daniel Morrison
-/
import Mathlib.Algebra.Group.Basic
import Mathlib.Algebra.Group.Prod

/-!
# Rota–Baxter operators on groups

A *Rota–Baxter operator* (of weight `1`) on a group `G` is a map `B : G → G` satisfying
`B x * B y = B (x * B x * y * (B x)⁻¹)` for all `x y : G`. Such an operator endows `G` with a
skew left brace structure, and hence produces a set-theoretic solution of the Yang–Baxter
equation.

This file introduces the predicate `IsRotaBaxter`, together with its additive counterpart
`IsAddRotaBaxter` (generated by `to_additive`), and develops a small API:

* `isRotaBaxter_one` and `inv_isRotaBaxter`: the constant map `1` and inversion are Rota–Baxter
  operators;
* `IsRotaBaxter.map_one`: a Rota–Baxter operator fixes the identity;
* `IsRotaBaxter.prodMap` and `Prod.map_isRotaBaxter`: behaviour under binary products;
* `isRotaBaxter_iff_mul`: on a commutative group, the Rota–Baxter operators are exactly the
  multiplicative maps.

## References

The notion of a Rota–Baxter operator on a group was introduced by L. Guo, H. Lang and Y. Sheng;
see also V. Bardakov and V. Gubarev, *Rota–Baxter operators on groups*.
-/

open Function

-- Available in mathlib for Lean ≥ 4.31; kept here for compatibility with the current toolchain.
/-- Inversion is a bijection of any type with involutive inversion. -/
@[to_additive /-- Negation is a bijection of any type with involutive negation. -/]
theorem inv_bijective {G : Type*} [InvolutiveInv G] : Bijective (Inv.inv : G → G) :=
  inv_involutive.bijective

/-! ## Rota–Baxter operators -/

section RotaBaxterGroup

variable {G H : Type*} [Group G] [Group H]
variable {B : G → G} {C : H → H}

/-- A **Rota–Baxter operator** (of weight `1`) on a group `G` is a map `B : G → G` satisfying
`B x * B y = B (x * B x * y * (B x)⁻¹)` for all `x y : G`. -/
@[to_additive IsAddRotaBaxter /-- An **additive Rota–Baxter operator** (of weight `1`) on an
additive group `G` is a map `B : G → G` satisfying `B x + B y = B (x + B x + y - B x)` for all
`x y : G`. -/]
def IsRotaBaxter (B : G → G) : Prop :=
  ∀ x y, B x * B y = B (x * B x * y * (B x)⁻¹)

/-- The constant map at `1` is a Rota–Baxter operator. -/
@[to_additive isAddRotaBaxter_zero /-- The constant map at `0` is an additive Rota–Baxter
operator. -/]
theorem isRotaBaxter_one : IsRotaBaxter (1 : G → G) :=
  fun x y ↦ by simp

/-- Inversion `x ↦ x⁻¹` is a Rota–Baxter operator. -/
@[to_additive neg_isAddRotaBaxter /-- Negation `x ↦ -x` is an additive Rota–Baxter operator. -/]
theorem inv_isRotaBaxter : IsRotaBaxter (Inv.inv : G → G) :=
  fun x y ↦ by simp

/-- A Rota–Baxter operator fixes the identity: `B 1 = 1`. -/
@[to_additive (attr := simp) /-- An additive Rota–Baxter operator fixes the zero: `B 0 = 0`. -/]
theorem IsRotaBaxter.map_one (hB : IsRotaBaxter B) : B 1 = 1 := by
  simpa using hB 1 1

/-- The product map of two Rota–Baxter operators is a Rota–Baxter operator. -/
@[to_additive /-- The product map of two additive Rota–Baxter operators is an additive
Rota–Baxter operator. -/]
theorem IsRotaBaxter.prodMap (hB : IsRotaBaxter B) (hC : IsRotaBaxter C) :
    IsRotaBaxter (Prod.map B C) :=
  fun x y ↦ by simp [Prod.map, hB x.1 y.1, hC x.2 y.2]

/-- `Prod.map B C` is a Rota–Baxter operator if and only if both `B` and `C` are. -/
@[to_additive (attr := simp) Prod.map_isAddRotaBaxter /-- `Prod.map B C` is an additive Rota–Baxter
operator if and only if both `B` and `C` are. -/]
theorem Prod.map_isRotaBaxter :
    IsRotaBaxter (Prod.map B C) ↔ IsRotaBaxter B ∧ IsRotaBaxter C := by
  refine ⟨fun h ↦ ⟨fun x₁ y₁ ↦ ?_, fun x₂ y₂ ↦ ?_⟩, fun h ↦ IsRotaBaxter.prodMap h.1 h.2⟩
  · simpa using congrArg Prod.fst (h (x₁, 1) (y₁, 1))
  · simpa using congrArg Prod.snd (h (1, x₂) (1, y₂))

end RotaBaxterGroup

section RotaBaxterCommGroup

variable {G : Type*} [CommGroup G]

/-- On a commutative group, a map is a Rota–Baxter operator if and only if it is multiplicative,
that is, `B (x * y) = B x * B y` for all `x y`. -/
@[to_additive (attr := simp) isAddRotaBaxter_iff_add /-- On an additive commutative group, a map is
an additive Rota–Baxter operator if and only if it is additive, that is, `B (x + y) = B x + B y`
for all `x y`. -/]
theorem isRotaBaxter_iff_mul (B : G → G) :
    IsRotaBaxter B ↔ ∀ x y, B (x * y) = B x * B y :=
  ⟨fun h x y ↦ by simp [h x y, mul_assoc], fun h x y ↦ by simp [h, mul_assoc]⟩

end RotaBaxterCommGroup
