/-
Copyright (c) 2026 Pietro Monticone. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aristotle (Harmonic), Elias Judin, Daniel Morrison
-/
import Kourovka.Mathlib.GroupTheory.Orderable.Dlab.Basic

/-!
# The Rank-One Slope Group for Kourovka 21.149

This file provides compatibility names for the Dlab-group formalization of Kourovka Notebook
Problem 21.149 and defines its subgroup of slopes generated by `2`.
-/

/-! ## Compatibility names -/

/-- The closed unit interval `[0, 1]`. -/
abbrev IntervalPoint := unitInterval

/-- The order automorphisms of the closed unit interval. -/
abbrev IntervalAut := Dlab.IntervalAut

/-- The multiplicative group of positive real slopes. -/
abbrev PositiveSlopeGroup := NNRealˣ

namespace IntervalAut

/-- Two interval automorphisms that agree pointwise are equal. -/
@[ext]
theorem ext (f g : IntervalAut) (h : ∀ x, f x = g x) : f = g := RelIso.ext h

/-- The identity interval automorphism acts as the identity. -/
@[simp]
theorem one_apply (x : IntervalPoint) : ((1 : IntervalAut) x) = x := rfl

/-- Multiplication of interval automorphisms is composition. -/
@[simp]
theorem mul_apply (f g : IntervalAut) (x : IntervalPoint) : (f * g) x = f (g x) := rfl

/-- The inverse interval automorphism is a left inverse of `f`. -/
@[simp]
theorem inv_apply_apply (f : IntervalAut) (x : IntervalPoint) : f⁻¹ (f x) = x :=
  f.symm_apply_apply x

/-- The inverse interval automorphism is a right inverse of `f`. -/
@[simp]
theorem apply_inv_apply (f : IntervalAut) (x : IntervalPoint) : f (f⁻¹ x) = x :=
  f.apply_symm_apply x

/-- Every interval order automorphism fixes `0`. -/
@[simp]
theorem map_zero (f : IntervalAut) : f 0 = 0 := f.map_bot

/-- Every interval order automorphism fixes `1`. -/
@[simp]
theorem map_one (f : IntervalAut) : f 1 = 1 := f.map_top

/-- Coerce a positive slope unit to a real number. -/
abbrev slopeToReal (h : PositiveSlopeGroup) : ℝ := ((h : NNReal) : ℝ)

end IntervalAut

/-- A compatibility name for the local right-linearity predicate. -/
abbrev IsLocallyRightHLinear := Dlab.IsLocallyRightHLinear

/-- A compatibility name for being the identity near `0`. -/
abbrev IsIdentityNearZero := Dlab.IsIdentityNearZero

/-- A compatibility name for being the identity near `1`. -/
abbrev IsIdentityNearOne := Dlab.IsIdentityNearOne

/-- A compatibility name for the Dlab-element predicate. -/
abbrev IsDlabElement := Dlab.IsElement

/-- Local right-linearity is preserved by multiplication. -/
alias isLocallyRightHLinear_mul := Dlab.isLocallyRightHLinear_mul

/-- Local right-linearity is preserved by inversion. -/
alias isLocallyRightHLinear_inv := Dlab.isLocallyRightHLinear_inv

/-- Being the identity near `0` is preserved by inversion. -/
alias isIdentityNearZero_inv := Dlab.isIdentityNearZero_inv

/-- Being the identity near `1` is preserved by inversion. -/
alias isIdentityNearOne_inv := Dlab.isIdentityNearOne_inv

/-- The identity interval automorphism is a Dlab element. -/
alias isDlabElement_one := Dlab.isElement_one

/-- Dlab elements are closed under multiplication. -/
alias isDlabElement_mul := Dlab.isElement_mul

/-- Dlab elements are closed under inversion. -/
alias isDlabElement_inv := Dlab.isElement_inv

/-- A compatibility name for the Dlab subgroup. -/
abbrev dlabSubgroup := Dlab.subgroup

/-! ## Rank-one slopes -/

/-- The slope `2`, as a positive real unit. -/
noncomputable def twoSlope : PositiveSlopeGroup := Units.mk0 (2 : NNReal) (by norm_num)

/-- The rank-one slope subgroup generated by `2`. -/
noncomputable def rankOneSlopeGroup : Subgroup PositiveSlopeGroup := Subgroup.zpowers twoSlope

/-- The slope `2` belongs to the rank-one slope subgroup `⟨2⟩`. -/
lemma twoSlope_mem_rankOne : twoSlope ∈ rankOneSlopeGroup := Subgroup.mem_zpowers twoSlope

/-- The slope `1 / 2` belongs to the rank-one slope subgroup `⟨2⟩`. -/
lemma twoSlope_inv_mem_rankOne : twoSlope⁻¹ ∈ rankOneSlopeGroup :=
  rankOneSlopeGroup.inv_mem twoSlope_mem_rankOne
