/-
Copyright (c) 2026 Pietro Monticone. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aristotle (Harmonic), Pietro Monticone, Daniel Morrison
-/
import Mathlib.Algebra.EuclideanDomain.Basic
import Mathlib.Algebra.EuclideanDomain.Int
import Mathlib.Algebra.Order.Ring.Star
import Mathlib.Analysis.Normed.Ring.Lemmas
import Mathlib.Data.Int.Star
import Mathlib.Order.BourbakiWitt
import Mathlib.Data.Nat.PrimeFin
import Mathlib.Tactic.IntervalCases

/-!
# Class Transpositions

For integers `0 ≤ r < m`, define the residue class `r(m) = {r + k·m | k ∈ ℤ}`.
For disjoint classes `r₁(m₁) ∩ r₂(m₂) = ∅`, the *class transposition*
`τ_{r₁(m₁), r₂(m₂)}` is the involution interchanging `r₁ + t·m₁` and `r₂ + t·m₂`
for each integer `t`, fixing everything else. Let `CT(ℤ)` be the group generated by
all class transpositions.
-/

section residueClass

/-- The residue class `{r + k * m | k ∈ ℤ}`, equivalently `{n ∈ ℤ | m ∣ n - r}`. -/
def residueClass (r m : ℤ) : Set ℤ :=
  {n | m ∣ (n - r)}

/-- Membership in the residue class: `n ∈ residueClass r m ↔ m ∣ (n - r)`. -/
lemma mem_residueClass_iff {r m n : ℤ} : n ∈ residueClass r m ↔ m ∣ (n - r) :=
  Iff.rfl

/-- The representative `r` belongs to its own residue class `residueClass r m`. -/
lemma self_mem_residueClass (r m : ℤ) : r ∈ residueClass r m := by simp [residueClass]

/-- Each `r + k * m` lies in the residue class `residueClass r m`. -/
lemma mem_residueClass_add_mul (r m k : ℤ) : r + k * m ∈ residueClass r m := by simp [residueClass]

/-- With modulus `0`, the residue class is the singleton `{r}`. -/
lemma residueClass_zero {r : ℤ} : residueClass r 0 = {r} := by simp [residueClass, sub_eq_zero]

/-- With modulus `1`, the residue class is all of `ℤ`. -/
lemma residueClass_one {r : ℤ} : residueClass r 1 = Set.univ := by simp [residueClass]

/-- Two residue classes are disjoint iff `gcd m₁ m₂ ∤ (r₁ - r₂)`. -/
lemma disjoint_iff_ndvd {r₁ m₁ r₂ m₂ : ℤ} :
    Disjoint (residueClass r₁ m₁) (residueClass r₂ m₂) ↔ ¬(m₁.gcd m₂ : ℤ) ∣ (r₁ - r₂) := by
  constructor <;> intro h
  · rw [Set.disjoint_left] at h
    contrapose! h
    obtain ⟨k, hk⟩ := m₁.gcd_eq_gcd_ab m₂ ▸ h
    refine ⟨r₁ - m₁ * m₁.gcdA m₂ * k, ?_, ?_⟩ <;> simp_all [residueClass]
    · exact dvd_mul_of_dvd_left (dvd_mul_right ..) _
    · refine ⟨k * m₁.gcdB m₂, by grind⟩
  · contrapose! h
    obtain ⟨n, hn₁, hn₂⟩ := Set.not_disjoint_iff.mp h
    obtain ⟨k₁, hk₁⟩ := hn₁
    obtain ⟨k₂, hk₂⟩ := hn₂
    rw [show r₁ - r₂ = (n - r₂) - (n - r₁) by ring]
    refine dvd_sub (dvd_trans (Int.gcd_dvd_right ..) ?_) (dvd_trans (Int.gcd_dvd_left ..) ?_) <;>
      aesop

end residueClass

section function

/-- The function sending elements of `residueClass r₁ m₁` to `residueClass r₂ m₂`
    via the index-preserving map `r₁ + t * m₁ ↦ r₂ + t * m₂`, and vice versa,
    fixing all other elements. -/
def τFun (r₁ m₁ r₂ m₂ : ℤ) (n : ℤ) : ℤ :=
  if m₁ ∣ (n - r₁) then r₂ + (n - r₁) / m₁ * m₂
  else if m₂ ∣ (n - r₂) then r₁ + (n - r₂) / m₂ * m₁ else n

/-- Value of `τFun` on the first class: if `m₁ ∣ (n - r₁)` then
`τFun r₁ m₁ r₂ m₂ n = r₂ + (n - r₁) / m₁ * m₂`. -/
lemma τFun_of_mem_class1 {r₁ m₁ r₂ m₂ n : ℤ} (h₁ : m₁ ∣ (n - r₁)) :
    τFun r₁ m₁ r₂ m₂ n = r₂ + (n - r₁) / m₁ * m₂ := by simp only [τFun, h₁, ↓reduceIte]

/-- Value of `τFun` on the second class: if `m₁ ∤ (n - r₁)` but `m₂ ∣ (n - r₂)` then
`τFun r₁ m₁ r₂ m₂ n = r₁ + (n - r₂) / m₂ * m₁`. -/
lemma τFun_of_mem_class2 {r₁ m₁ r₂ m₂ n : ℤ} (h₁ : ¬m₁ ∣ (n - r₁)) (h₂ : m₂ ∣ (n - r₂)) :
    τFun r₁ m₁ r₂ m₂ n = r₁ + (n - r₂) / m₂ * m₁ := by simp only [τFun, h₁, ↓reduceIte, h₂]

/-- `τFun` fixes any `n` lying in neither residue class. -/
lemma τFun_of_not_mem {r₁ m₁ r₂ m₂ n : ℤ} (h₁ : ¬m₁ ∣ (n - r₁)) (h₂ : ¬m₂ ∣ (n - r₂)) :
    τFun r₁ m₁ r₂ m₂ n = n := by simp only [τFun, h₁, ↓reduceIte, h₂]

/-- `τFun` sends the first class into the second: `m₂ ∣ (τFun r₁ m₁ r₂ m₂ n - r₂)`. -/
lemma τFun_image_in_class2 {r₁ m₁ r₂ m₂ n : ℤ} (h₁ : m₁ ∣ (n - r₁)) :
    m₂ ∣ (τFun r₁ m₁ r₂ m₂ n - r₂) := by
  simp [τFun_of_mem_class1 h₁]

/-- `τFun` sends the second class into the first: `m₁ ∣ (τFun r₁ m₁ r₂ m₂ n - r₁)`. -/
lemma τFun_image_in_class1 {r₁ m₁ r₂ m₂ n : ℤ} (h₁ : ¬m₁ ∣ (n - r₁)) (h₂ : m₂ ∣ (n - r₂)) :
    m₁ ∣ (τFun r₁ m₁ r₂ m₂ n - r₁) := by
  simp [τFun_of_mem_class2 h₁ h₂]

/-- For disjoint classes, a point of the first class is not in the second: `¬m₂ ∣ (n - r₂)`. -/
lemma not_mem_class2_of_mem_class1_disjoint {r₁ m₁ r₂ m₂ n : ℤ} (h₁ : m₁ ∣ (n - r₁))
    (hdisjoint : Disjoint (residueClass r₁ m₁) (residueClass r₂ m₂)) : ¬m₂ ∣ (n - r₂) :=
  fun h₂ ↦ Set.disjoint_iff.mp hdisjoint ⟨h₁, h₂⟩

/-- `τFun` is involutive on the first class: applying it twice to such an `n` returns `n`. -/
lemma τFun_invol_class1 {r₁ m₁ r₂ m₂ n : ℤ} (hm₂ : m₂ ≠ 0) (h₁ : m₁ ∣ (n - r₁))
    (hdisjoint : Disjoint (residueClass r₁ m₁) (residueClass r₂ m₂)) :
    τFun r₁ m₁ r₂ m₂ (τFun r₁ m₁ r₂ m₂ n) = n := by
  contrapose! hdisjoint
  unfold τFun at *
  by_cases hm₁ : m₁ = 0 <;> simp_all [residueClass]
  · simp_all only [sub_eq_iff_eq_add, zero_add, ite_self, not_true_eq_false]
  · split_ifs at hdisjoint <;> simp_all [Set.disjoint_left]
    · aesop
    · refine False.elim <| hdisjoint <| ?_
      rw [Int.ediv_mul_cancel h₁, add_sub_cancel]

/-- `τFun` is involutive on the second class: applying it twice to such an `n` returns `n`. -/
lemma τFun_invol_class2 {r₁ m₁ r₂ m₂ n : ℤ} (hm₁ : m₁ ≠ 0) (h₁ : ¬m₁ ∣ (n - r₁))
    (h₂ : m₂ ∣ (n - r₂)) : τFun r₁ m₁ r₂ m₂ (τFun r₁ m₁ r₂ m₂ n) = n := by
  unfold τFun
  split_ifs <;> simp_all [← eq_sub_iff_add_eq']
  rw [Int.ediv_mul_cancel h₂]

/-- For nonzero moduli with disjoint residue classes, `τFun r₁ m₁ r₂ m₂` is an involution. -/
theorem τ_involutive (r₁ m₁ r₂ m₂ : ℤ) (hm₁ : m₁ ≠ 0) (hm₂ : m₂ ≠ 0)
    (hdisjoint : Disjoint (residueClass r₁ m₁) (residueClass r₂ m₂)) :
    (τFun r₁ m₁ r₂ m₂).Involutive := by
  intro n
  by_cases h₁ : m₁ ∣ (n - r₁)
  · exact τFun_invol_class1 hm₂ h₁ hdisjoint
  · by_cases h₂ : m₂ ∣ (n - r₂)
    · exact τFun_invol_class2 hm₁ h₁ h₂
    · simp [τFun_of_not_mem h₁ h₂]

end function

section perm

/-- The permutation of `ℤ` that swaps `r₁ + t * m₁` with `r₂ + t * m₂` for each `t ∈ ℤ`,
    keeping all other integers fixed. If `m₁ = 0` or `m₂ = 0` or the residue classes are not
    disjoint then is the identity permutation. -/
def τ (r₁ m₁ r₂ m₂ : ℤ) : Equiv.Perm ℤ :=
  if hm₁ : m₁ = 0 then Equiv.refl ℤ
  else
    if hm₂ : m₂ = 0 then Equiv.refl ℤ
    else
      if h : (m₁.gcd m₂ : ℤ) ∣ (r₁ - r₂) then Equiv.refl ℤ
      else (τ_involutive r₁ m₁ r₂ m₂ hm₁ hm₂ (disjoint_iff_ndvd.mpr h)).toPerm _

/-- The class transposition with left modulus `0` is the identity permutation. -/
lemma τ_zero_left (r₁ r₂ m₂ : ℤ) : τ r₁ 0 r₂ m₂ = 1 :=
  rfl

/-- The class transposition with right modulus `0` is the identity permutation. -/
lemma τ_zero_right (r₁ m₁ r₂ : ℤ) : τ r₁ m₁ r₂ 0 = 1 := by
  simp only [τ, ↓reduceDIte, dite_eq_ite, ite_self]
  rfl

/-- When `gcd m₁ m₂ ∣ (r₁ - r₂)` (the classes are not disjoint), `τ r₁ m₁ r₂ m₂` is the identity. -/
lemma τ_dvd {r₁ m₁ r₂ m₂ : ℤ} (h : (m₁.gcd m₂ : ℤ) ∣ (r₁ - r₂)) : τ r₁ m₁ r₂ m₂ = 1 := by
  unfold τ
  split_ifs <;> rfl

/-- When the moduli are nonzero and the classes disjoint, `τ` acts pointwise as `τFun`. -/
lemma τ_apply {r₁ m₁ r₂ m₂ : ℤ} (hm₁ : m₁ ≠ 0) (hm₂ : m₂ ≠ 0) (h : ¬(m₁.gcd m₂ : ℤ) ∣ (r₁ - r₂))
    (n : ℤ) : τ r₁ m₁ r₂ m₂ n = τFun r₁ m₁ r₂ m₂ n := by
  unfold τ
  split_ifs with h <;> try contradiction
  simp

/-- If `τ r₁ m₁ r₂ m₂ ≠ 1` then the left modulus is nonzero: `m₁ ≠ 0`. -/
lemma ne_zero_left_of_τ_ne_one {r₁ m₁ r₂ m₂ : ℤ} (hτ : τ r₁ m₁ r₂ m₂ ≠ 1) : m₁ ≠ 0 := by
  rintro rfl
  exact hτ (τ_zero_left ..)

/-- If `τ r₁ m₁ r₂ m₂ ≠ 1` then the right modulus is nonzero: `m₂ ≠ 0`. -/
lemma ne_zero_right_of_τ_ne_one {r₁ m₁ r₂ m₂ : ℤ} (hτ : τ r₁ m₁ r₂ m₂ ≠ 1) : m₂ ≠ 0 := by
  rintro rfl
  exact hτ (τ_zero_right ..)

/-- If `τ r₁ m₁ r₂ m₂ ≠ 1` then the classes are disjoint: `gcd m₁ m₂ ∤ (r₁ - r₂)`. -/
lemma ndvd_of_τ_ne_one {r₁ m₁ r₂ m₂ : ℤ} (hτ : τ r₁ m₁ r₂ m₂ ≠ 1) : ¬(m₁.gcd m₂ : ℤ) ∣ (r₁ - r₂) :=
  fun h ↦ hτ (τ_dvd h)

/-- A nontrivial class transposition acts pointwise as `τFun`. -/
lemma τ_apply_ne_one {r₁ m₁ r₂ m₂ : ℤ} (hτ : τ r₁ m₁ r₂ m₂ ≠ 1) (n : ℤ) :
    τ r₁ m₁ r₂ m₂ n = τFun r₁ m₁ r₂ m₂ n :=
  τ_apply (ne_zero_left_of_τ_ne_one hτ) (ne_zero_right_of_τ_ne_one hτ) (ndvd_of_τ_ne_one hτ) n

/-- A nontrivial `τ` on a point of the first class: `τ r₁ m₁ r₂ m₂ n = r₂ + (n - r₁) / m₁ * m₂`. -/
lemma τ_apply_dvd₁ {r₁ m₁ r₂ m₂ n : ℤ} (hτ : τ r₁ m₁ r₂ m₂ ≠ 1) (hn : m₁ ∣ (n - r₁)) :
    τ r₁ m₁ r₂ m₂ n = r₂ + (n - r₁) / m₁ * m₂ := by
  rw [τ_apply_ne_one hτ]
  exact τFun_of_mem_class1 hn

/-- A nontrivial `τ` on a point of the second class: `τ r₁ m₁ r₂ m₂ n = r₁ + (n - r₂) / m₂ * m₁`. -/
lemma τ_apply_dvd₂ {r₁ m₁ r₂ m₂ n : ℤ} (hτ : τ r₁ m₁ r₂ m₂ ≠ 1) (hn : m₂ ∣ (n - r₂)) :
    τ r₁ m₁ r₂ m₂ n = r₁ + (n - r₂) / m₂ * m₁ := by
  rw [τ_apply_ne_one hτ]
  exact τFun_of_mem_class2
    (not_mem_class2_of_mem_class1_disjoint hn (disjoint_iff_ndvd.mpr (ndvd_of_τ_ne_one hτ)).symm) hn

/-- A nontrivial `τ` fixes any point lying in neither residue class. -/
lemma τ_apply_ndvd {r₁ m₁ r₂ m₂ n : ℤ} (hτ : τ r₁ m₁ r₂ m₂ ≠ 1) (hn₁ : ¬m₁ ∣ (n - r₁))
    (hn₂ : ¬m₂ ∣ (n - r₂)) : τ r₁ m₁ r₂ m₂ n = n := by
  rw [τ_apply_ne_one hτ]
  exact τFun_of_not_mem hn₁ hn₂

/-- A nontrivial `τ` swaps the representatives: `τ r₁ m₁ r₂ m₂ r₁ = r₂`. -/
lemma τ_apply_r₁ {r₁ m₁ r₂ m₂ : ℤ} (hτ : τ r₁ m₁ r₂ m₂ ≠ 1) : τ r₁ m₁ r₂ m₂ r₁ = r₂ := by
  rw [τ_apply_dvd₁ hτ] <;> simp

/-- A nontrivial `τ` swaps the representatives: `τ r₁ m₁ r₂ m₂ r₂ = r₁`. -/
lemma τ_apply_r₂ {r₁ m₁ r₂ m₂ : ℤ} (hτ : τ r₁ m₁ r₂ m₂ ≠ 1) : τ r₁ m₁ r₂ m₂ r₂ = r₁ := by
  rw [τ_apply_dvd₂ hτ] <;> simp

/-- A nontrivial `τ` maps the indexed point `r₁ + k * m₁` to `r₂ + k * m₂`. -/
lemma τ_apply_mul_add_r₁ {r₁ m₁ r₂ m₂ k : ℤ} (hτ : τ r₁ m₁ r₂ m₂ ≠ 1) :
    τ r₁ m₁ r₂ m₂ (r₁ + k * m₁) = r₂ + k * m₂ := by
  rw [τ_apply_dvd₁ hτ] <;> simp [ne_zero_left_of_τ_ne_one hτ]

/-- A nontrivial `τ` maps the indexed point `r₂ + k * m₂` to `r₁ + k * m₁`. -/
lemma τ_apply_mul_add_r₂ {r₁ m₁ r₂ m₂ k : ℤ} (hτ : τ r₁ m₁ r₂ m₂ ≠ 1) :
    τ r₁ m₁ r₂ m₂ (r₂ + k * m₂) = r₁ + k * m₁ := by
  rw [τ_apply_dvd₂ hτ] <;> simp [ne_zero_right_of_τ_ne_one hτ]

/-- Recover the left modulus from a nontrivial `τ`:
`m₁ = τ r₁ m₁ r₂ m₂ (r₂ + m₂) - τ r₁ m₁ r₂ m₂ r₂`. -/
lemma m₁_eq_τ_sub {r₁ m₁ r₂ m₂ : ℤ} (hτ : τ r₁ m₁ r₂ m₂ ≠ 1) :
    m₁ = τ r₁ m₁ r₂ m₂ (r₂ + m₂) - τ r₁ m₁ r₂ m₂ r₂ := by
  nth_rw 2 [← one_mul m₂]
  rw [τ_apply_mul_add_r₂ hτ, τ_apply_r₂ hτ]
  ring

/-- Recover the right modulus from a nontrivial `τ`:
`m₂ = τ r₁ m₁ r₂ m₂ (r₁ + m₁) - τ r₁ m₁ r₂ m₂ r₁`. -/
lemma m₂_eq_τ_sub {r₁ m₁ r₂ m₂ : ℤ} (hτ : τ r₁ m₁ r₂ m₂ ≠ 1) :
    m₂ = τ r₁ m₁ r₂ m₂ (r₁ + m₁) - τ r₁ m₁ r₂ m₂ r₁ := by
  nth_rw 2 [← one_mul m₁]
  rw [τ_apply_mul_add_r₁ hτ, τ_apply_r₁ hτ]
  ring

end perm

section subgroups

/-- The set of all class transpositions with moduli `m₁` and `m₂`. Note that this is only non-empty
for positive `m₁` and `m₂`. -/
def CT_generators (m₁ m₂ : ℤ) : Set (Equiv.Perm ℤ) :=
  {σ | ∃ r₁ ∈ Set.Ico 0 m₁, ∃ r₂ ∈ Set.Ico 0 m₂, σ = τ r₁ m₁ r₂ m₂}

/-- The subgroup generated by the class transpositions with moduli `m₁` and `m₂`. -/
def CT_pair (m₁ m₂ : ℤ) : Subgroup (Equiv.Perm ℤ) :=
  Subgroup.closure (CT_generators m₁ m₂)

/-- The subgroup generated by class transpositions with the same modulus `d` between 2 and `k`. -/
def CT_same (k : ℤ) : Subgroup (Equiv.Perm ℤ) :=
  ⨆ d ∈ Finset.Icc 2 k, CT_pair d d

/-- The subgroup generated by class transpositions with moduli whose prime factors lie in the set
`P`. -/
def CT_factor (P : Set ℕ) : Subgroup (Equiv.Perm ℤ) :=
  ⨆ m₁ ∈ {m | m.natAbs.primeFactors ⊆ P}, ⨆ m₂ ∈ {m | m.natAbs.primeFactors ⊆ P}, CT_pair m₁ m₂

/-- The subgroup generated by class transpositions with moduli that divide `m`. -/
def CT_dvd (m : ℤ) : Subgroup (Equiv.Perm ℤ) :=
  ⨆ m₁ ∈ {d | d ∣ m}, ⨆ m₂ ∈ {d | d ∣ m}, CT_pair m₁ m₂

/-- The subgroup generated by all class transpositions. -/
def CT : Subgroup (Equiv.Perm ℤ) :=
  ⨆ m₁, ⨆ m₂, CT_pair m₁ m₂

/-- `CT` is the subgroup generated by the union of all class-transposition generators. -/
lemma CT_eq_closure_iUnion : CT = Subgroup.closure (⋃ m₁, ⋃ m₂, CT_generators m₁ m₂) := by
  simp [CT, CT_pair, Subgroup.closure_iUnion]

/-- Membership in `CT_generators m₁ m₂`: `σ` is some `τ r₁ m₁ r₂ m₂` with representatives
`r₁ ∈ Set.Ico 0 m₁` and `r₂ ∈ Set.Ico 0 m₂`. -/
@[simp]
lemma mem_CT_generators_iff {m₁ m₂ : ℤ} {σ : Equiv.Perm ℤ} :
    σ ∈ CT_generators m₁ m₂ ↔ ∃ r₁ ∈ Set.Ico 0 m₁, ∃ r₂ ∈ Set.Ico 0 m₂, σ = τ r₁ m₁ r₂ m₂ :=
  Iff.rfl

/-- Each `τ r₁ m₁ r₂ m₂` with representatives in range is a generator in `CT_generators m₁ m₂`. -/
lemma τ_mem_CT_generators {m₁ m₂ r₁ r₂ : ℤ} (hr₁ : r₁ ∈ Set.Ico 0 m₁) (hr₂ : r₂ ∈ Set.Ico 0 m₂) :
    τ r₁ m₁ r₂ m₂ ∈ CT_generators m₁ m₂ :=
  ⟨r₁, hr₁, r₂, hr₂, rfl⟩

/-- The generators are contained in the subgroup they generate, `CT_pair m₁ m₂`. -/
lemma CT_generators_subset_closure (m₁ m₂ : ℤ) : CT_generators m₁ m₂ ⊆ ↑(CT_pair m₁ m₂) :=
  Subgroup.subset_closure

/-- There are no generators with nonpositive left modulus: `CT_generators m₁ m₂ = ∅`. -/
lemma CT_generators_empty_of_nonpos_left {m₁ m₂ : ℤ} (hm₁ : m₁ ≤ 0) : CT_generators m₁ m₂ = ∅ := by
  ext σ
  simp [CT_generators, hm₁]

/-- There are no generators with nonpositive right modulus: `CT_generators m₁ m₂ = ∅`. -/
lemma CT_generators_empty_of_nonpos_right {m₁ m₂ : ℤ} (hm₂ : m₂ ≤ 0) : CT_generators m₁ m₂ = ∅ := by
  simp [CT_generators, hm₂]

/-- `CT_pair m₁ m₂` unfolds to the closure of `CT_generators m₁ m₂`. -/
lemma CT_pair_def (m₁ m₂ : ℤ) : CT_pair m₁ m₂ = Subgroup.closure (CT_generators m₁ m₂) :=
  rfl

/-- Each generator `τ r₁ m₁ r₂ m₂` lies in `CT_pair m₁ m₂`. -/
lemma τ_mem_CT_pair {m₁ m₂ r₁ r₂ : ℤ} (hr₁ : r₁ ∈ Set.Ico 0 m₁) (hr₂ : r₂ ∈ Set.Ico 0 m₂) :
    τ r₁ m₁ r₂ m₂ ∈ CT_pair m₁ m₂ :=
  Subgroup.subset_closure (τ_mem_CT_generators hr₁ hr₂)

/-- `CT_pair m₁ m₂` is trivial when the left modulus is nonpositive. -/
lemma CT_pair_eq_bot_of_nonpos_left {m₁ m₂ : ℤ} (hm₁ : m₁ ≤ 0) : CT_pair m₁ m₂ = ⊥ := by
  rw [CT_pair_def, CT_generators_empty_of_nonpos_left hm₁, Subgroup.closure_empty]

/-- `CT_pair m₁ m₂` is trivial when the right modulus is nonpositive. -/
lemma CT_pair_eq_bot_of_nonpos_right {m₁ m₂ : ℤ} (hm₂ : m₂ ≤ 0) : CT_pair m₁ m₂ = ⊥ :=
  Subgroup.closure_eq_bot_iff.mpr (by simp [CT_generators_empty_of_nonpos_right hm₂])

/-- `CT_same k` unfolds to the supremum of `CT_pair d d` over `d ∈ Finset.Icc 2 k`. -/
@[simp]
lemma CT_same_eq_sup_CT_pair (k : ℤ) : CT_same k = ⨆ d ∈ Finset.Icc 2 k, CT_pair d d :=
  rfl

/-- Each equal-modulus generator `τ r₁ d r₂ d` with `d ∈ Finset.Icc 2 k` lies in `CT_same k`. -/
lemma τ_mem_CT_same {k d r₁ r₂ : ℤ} (hd : d ∈ Finset.Icc 2 k) (hr₁ : r₁ ∈ Set.Ico 0 d)
    (hr₂ : r₂ ∈ Set.Ico 0 d) : τ r₁ d r₂ d ∈ CT_same k := by
  unfold CT_same
  apply Subgroup.mem_iSup_of_mem d
  apply Subgroup.mem_iSup_of_mem hd
  exact τ_mem_CT_pair hr₁ hr₂

/-- `CT_same k` is trivial for `k < 2`. -/
lemma CT_same_eq_bot_of_lt_two {k : ℤ} (hk : k < 2) : CT_same k = ⊥ := by
  simp only [CT_same, iSup_eq_bot, Finset.mem_Icc]
  exact fun i hi ↦ absurd hi (by omega)

/-- `CT_factor P` unfolds to the supremum of `CT_pair m₁ m₂` over moduli whose prime factors
lie in `P`. -/
lemma CT_factor_def (P : Set ℕ) : CT_factor P =
    ⨆ m₁ ∈ {m | m.natAbs.primeFactors ⊆ P}, ⨆ m₂ ∈ {m | m.natAbs.primeFactors ⊆ P}, CT_pair m₁ m₂ :=
  rfl

/-- If both moduli have prime factors in `P`, then `CT_pair m₁ m₂ ≤ CT_factor P`. -/
lemma CT_pair_le_CT_factor {P : Set ℕ} {m₁ m₂ : ℤ} (h₁ : ↑m₁.natAbs.primeFactors ⊆ P)
    (h₂ : ↑m₂.natAbs.primeFactors ⊆ P) : CT_pair m₁ m₂ ≤ CT_factor P :=
  le_iSup₂_of_le m₁ h₁ (le_iSup₂_of_le m₂ h₂ le_rfl)

/-- Each `τ r₁ m₁ r₂ m₂` with both moduli supported on `P` lies in `CT_factor P`. -/
lemma τ_mem_CT_factor {P : Set ℕ} {m₁ m₂ r₁ r₂ : ℤ} (h₁ : ↑m₁.natAbs.primeFactors ⊆ P)
    (h₂ : ↑m₂.natAbs.primeFactors ⊆ P) (hr₁ : r₁ ∈ Set.Ico 0 m₁) (hr₂ : r₂ ∈ Set.Ico 0 m₂) :
    τ r₁ m₁ r₂ m₂ ∈ CT_factor P :=
  CT_pair_le_CT_factor h₁ h₂ (τ_mem_CT_pair hr₁ hr₂)

/-- `CT_factor` is monotone in the set of allowed primes: `P ⊆ Q → CT_factor P ≤ CT_factor Q`. -/
lemma CT_factor_mono {P Q : Set ℕ} (h : P ⊆ Q) : CT_factor P ≤ CT_factor Q :=
  iSup₂_le fun _ hm₁ ↦
    iSup₂_le fun _ hm₂ ↦ CT_pair_le_CT_factor (fun _ a_1 ↦ h (hm₁ a_1)) fun _ a_1 ↦ h (hm₂ a_1)

/-- `CT_factor ∅` is trivial. -/
lemma CT_factor_empty : CT_factor ∅ = ⊥ := by
  refine le_antisymm (iSup_le ?_) bot_le
  simp only [Set.subset_empty_iff, Finset.coe_eq_empty, Nat.primeFactors_eq_empty,
    Int.natAbs_eq_zero, Set.mem_setOf_eq, le_bot_iff, iSup_eq_bot, forall_eq_or_imp]
  constructor
  · simp [CT_pair_eq_bot_of_nonpos_left]
  · intro a ha
    have h_abs : a = 1 ∨ a = -1 := Int.natAbs_eq_iff.mp ha
    rcases h_abs with (rfl | rfl) <;>
      simp [CT_pair_eq_bot_of_nonpos_left, CT_pair_eq_bot_of_nonpos_right]
    intro a ha
    rw [Int.natAbs_eq_iff] at ha
    rcases ha with (rfl | rfl) <;> simp [CT_pair_eq_bot_of_nonpos_right]
    rw [CT_pair, Subgroup.closure_eq_bot_iff]
    rintro σ ⟨r₁, hr₁, r₂, hr₂, rfl⟩
    simp_all only [Set.mem_Ico, Set.mem_singleton_iff]
    refine τ_dvd ?_
    norm_num [show r₁ = 0 by linarith, show r₂ = 0 by linarith]

/-- `CT_dvd m` unfolds to the supremum of `CT_pair m₁ m₂` over divisors `m₁, m₂` of `m`. -/
lemma CT_dvd_def (m : ℤ) : CT_dvd m = ⨆ m₁ ∈ {d | d ∣ m}, ⨆ m₂ ∈ {d | d ∣ m}, CT_pair m₁ m₂ :=
  rfl

/-- If both moduli divide `m`, then `CT_pair m₁ m₂ ≤ CT_dvd m`. -/
lemma CT_pair_le_CT_dvd {m m₁ m₂ : ℤ} (h₁ : m₁ ∣ m) (h₂ : m₂ ∣ m) : CT_pair m₁ m₂ ≤ CT_dvd m :=
  le_iSup₂_of_le m₁ (by aesop) (le_iSup₂_of_le m₂ (by aesop) (by aesop))

/-- Each `τ r₁ m₁ r₂ m₂` with `m₁ ∣ m` and `m₂ ∣ m` lies in `CT_dvd m`. -/
lemma τ_mem_CT_dvd {m m₁ m₂ r₁ r₂ : ℤ} (h₁ : m₁ ∣ m) (h₂ : m₂ ∣ m) (hr₁ : r₁ ∈ Set.Ico 0 m₁)
    (hr₂ : r₂ ∈ Set.Ico 0 m₂) : τ r₁ m₁ r₂ m₂ ∈ CT_dvd m :=
  CT_pair_le_CT_dvd h₁ h₂ (τ_mem_CT_pair hr₁ hr₂)

/-- `CT_dvd` is monotone under divisibility: `m ∣ n → CT_dvd m ≤ CT_dvd n`. -/
lemma CT_dvd_mono {m n : ℤ} (h : m ∣ n) : CT_dvd m ≤ CT_dvd n := by
  simp only [CT_dvd_def, Set.mem_setOf_eq, le_iSup_iff, iSup_le_iff]
  exact fun b hb i hi j hj ↦ hb i (dvd_trans hi h) j (dvd_trans hj h)

/-- Every modulus divides `0`, so `CT_dvd 0 = CT`. -/
lemma CT_dvd_zero : CT_dvd 0 = CT := by refine le_antisymm ?_ ?_ <;> simp [CT_dvd_def, CT]

/-- `CT_dvd 1` is trivial. -/
lemma CT_dvd_one : CT_dvd 1 = ⊥ := by
  refine le_antisymm ?_ ?_
  · refine iSup₂_le fun m₁ hm₁ ↦ iSup₂_le fun m₂ hm₂ ↦ ?_
    rcases Int.isUnit_iff.mp (isUnit_of_dvd_one hm₁) with (rfl | rfl) <;>
        rcases Int.isUnit_iff.mp (isUnit_of_dvd_one hm₂) with (rfl | rfl) <;>
      simp [CT_pair]
    intro y x hx₁ hx₂ z hz₁ hz₂ hy
    subst hy
    interval_cases x
    interval_cases z
    rw [τ]
    rfl
  · exact bot_le

/-- `CT_dvd` is invariant under negating the modulus: `CT_dvd (-m) = CT_dvd m`. -/
lemma CT_dvd_neg (m : ℤ) : CT_dvd (-m) = CT_dvd m :=
  le_antisymm (iSup₂_le fun _ hm₁ ↦ iSup₂_le fun _ hm₂ ↦ CT_pair_le_CT_dvd (dvd_neg.mp hm₁)
    (dvd_neg.mp hm₂)) (iSup₂_le fun _ hm₁ ↦ iSup₂_le fun _ hm₂ ↦ CT_pair_le_CT_dvd (dvd_neg.mpr hm₁)
      (dvd_neg.mpr hm₂))

/-- `CT` unfolds to the supremum of `CT_pair m₁ m₂` over all moduli. -/
lemma CT_def : CT = ⨆ m₁, ⨆ m₂, CT_pair m₁ m₂ :=
  rfl

/-- Each `CT_pair m₁ m₂` is contained in `CT`. -/
lemma CT_pair_le_CT (m₁ m₂ : ℤ) : CT_pair m₁ m₂ ≤ CT :=
  le_iSup_of_le m₁ (le_iSup_of_le m₂ (le_rfl))

/-- Each generator `τ r₁ m₁ r₂ m₂` lies in `CT`. -/
lemma τ_mem_CT {m₁ m₂ r₁ r₂ : ℤ} (hr₁ : r₁ ∈ Set.Ico 0 m₁) (hr₂ : r₂ ∈ Set.Ico 0 m₂) :
    τ r₁ m₁ r₂ m₂ ∈ CT :=
  CT_pair_le_CT m₁ m₂ (τ_mem_CT_pair hr₁ hr₂)

/-- `CT_same k` is contained in `CT`. -/
lemma CT_same_le_CT (k : ℤ) : CT_same k ≤ CT :=
  iSup₂_le fun _ _ ↦ CT_pair_le_CT _ _

/-- `CT_dvd m` is contained in `CT`. -/
lemma CT_dvd_le_CT (m : ℤ) : CT_dvd m ≤ CT :=
  iSup₂_le fun m₁ _ ↦ iSup₂_le fun m₂ _ ↦ CT_pair_le_CT m₁ m₂

/-- `CT_factor P` is contained in `CT`. -/
lemma CT_factor_le_CT (P : Set ℕ) : CT_factor P ≤ CT :=
  iSup₂_le fun m₁ _ ↦ iSup₂_le fun m₂ _ ↦ CT_pair_le_CT m₁ m₂

/-- `CT` is the supremum of the `CT_dvd m` over all integers `m`. -/
lemma CT_eq_iSup_CT_dvd : CT = ⨆ m, CT_dvd m := by
  refine le_antisymm ?_ <| iSup_le fun m ↦ CT_dvd_le_CT m
  exact iSup₂_le fun m₁ m₂ ↦ le_trans (CT_pair_le_CT_dvd (dvd_mul_right m₁ m₂)
    (dvd_mul_left m₂ m₁)) (le_iSup (fun m ↦ CT_dvd m) (m₁ * m₂))

end subgroups
