/-
Copyright (c) 2026 Pietro Monticone. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Pietro Monticone, Aristotle (Harmonic)
-/

import Mathlib.Algebra.Group.End
import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic
import Mathlib.Data.NNReal.Basic
import Mathlib.Order.RelClasses
import Mathlib.Tactic
import Mathlib.Topology.Homeomorph.Lemmas
import Mathlib.Topology.Instances.Real.Lemmas
import Mathlib.Topology.Order.MonotoneConvergence
import Mathlib.Topology.UnitInterval

/-!
# Kourovka Notebook Problem 21.149

Are there order automorphisms of Dlab groups that are not inner automorphisms?

We answer the question in the affirmative for `H = ⟨2⟩ ≤ ℝ_{>0}`: the
piecewise-linear homeomorphism with slopes `2` on `[0, 1/3]` and `1/2` on
`[1/3, 1]` normalises `G_⟨2⟩` by conjugation, preserves the natural bi-invariant
first-disagreement order, and yet is not itself an element of `G_⟨2⟩`. It
therefore induces an order automorphism of `G_⟨2⟩` that is not inner.

## Main results

* `IntervalAut` — the group of increasing autohomeomorphisms of `[0, 1]`.
* `DlabGroup H` — Dlab's group `G_H`.
* `rankOneDlabOrder` — a bi-invariant linear order on `G_⟨2⟩`.
* `rankOneConjOrderAut` — the order automorphism induced by conjugation by the
  rank-one PL homeomorphism with slopes `2` and `1/2`.
* `rankOneConjOrderAut_not_inner` — `rankOneConjOrderAut` is not inner.
* `existsDlabGroupOrderAutNotInner` — there exists a Dlab group with a non-inner
  order automorphism, settling Kourovka 21.149.

## Proof outline

1. Set up `IntervalAut` and the subgroup `DlabGroup H` of locally right
   `H`-linear elements that are the identity near the boundary.
2. Construct `conjAut : IntervalAut`, a piecewise-linear homeomorphism with
   slopes `2` and `1/2`, and check that conjugation by it preserves `G_⟨2⟩`,
   yielding the group automorphism `conjMulEquiv`.
3. Show that any element of `G_⟨2⟩` fixed by `conjMulEquiv` is the identity, by
   an orbit-growth argument: from the identity-near-`0` condition, the fixed
   set already contains an interval `[0, r]` with `r > 0`, and conjugation by
   `conjAut` enlarges it to `[0, conjAut r]`; iterating gives a sequence
   `r, conjAut r, conjAut² r, …` increasing to the unique fixed point `1` of
   `conjReal` in `(0, 1]`, whence the fixed set fills `[0, 1]`.
4. Equip `G_⟨2⟩` with the *first-disagreement* relation `fd_lt`: declare
   `f < g` if there is a point `x` such that `f x < g x` and `g y ≥ f y` for
   all `y < x`. Verify that `fd_lt` is irreflexive, transitive, trichotomous,
   and bi-translation-invariant, hence defines a bi-invariant linear order
   `rankOneDlabOrder` on `G_⟨2⟩`. Show that `conjMulEquiv` preserves it.
5. Conclude that `conjMulEquiv` is an order automorphism. By step 3, no inner
   automorphism can equal `conjMulEquiv` (else the conjugating element would be
   fixed, hence trivial, contradicting that `conjMulEquiv` moves a chosen
   bump witness). This gives `rankOneConjOrderAut_not_inner`, and packaging
   yields `existsDlabGroupOrderAutNotInner`.
-/

namespace MulAut

variable (G : Type*) [Group G]

/-- The subgroup of inner automorphisms of `G`. -/
def innerSubgroup : Subgroup (MulAut G) :=
  MonoidHom.range (conj : G →* MulAut G)

end MulAut

open scoped unitInterval Topology

namespace KourovkaNotebook
namespace Solution21_149

/-! ### The unit interval and slope groups -/

/-- The closed unit interval `[0,1]` as a subtype of `ℝ`. -/
abbrev IntervalPoint :=
  ↥(Set.Icc (0 : ℝ) 1)

/-- The multiplicative group of positive real slopes, represented as units of `ℝ≥0`. -/
abbrev PositiveSlopeGroup :=
  Units NNReal

/-- The slope `2`, as a positive real unit. -/
noncomputable def twoSlope : PositiveSlopeGroup :=
  Units.mk0 (2 : NNReal) (by norm_num)

/-- The rank-one slope subgroup generated by `2`. -/
noncomputable def rankOneSlopeGroup : Subgroup PositiveSlopeGroup :=
  Subgroup.zpowers twoSlope

/-- The slope `2` belongs to the rank-one slope subgroup `⟨2⟩`. -/
lemma twoSlope_mem_rankOne : twoSlope ∈ rankOneSlopeGroup :=
  Subgroup.mem_zpowers twoSlope

/-- The slope `1/2` belongs to the rank-one slope subgroup `⟨2⟩`. -/
lemma twoSlope_inv_mem_rankOne : twoSlope⁻¹ ∈ rankOneSlopeGroup :=
  rankOneSlopeGroup.inv_mem twoSlope_mem_rankOne

/-! ### Increasing autohomeomorphisms of `[0,1]` -/

/-- An increasing autohomeomorphism of the closed unit interval `[0,1]`. This is a
homeomorphism that is strictly monotone. -/
structure IntervalAut where
  /-- The underlying autohomeomorphism of `[0,1]`. -/
  toHomeomorph : Homeomorph IntervalPoint IntervalPoint
  /-- Strict monotonicity of the underlying map. -/
  strictMono : StrictMono toHomeomorph

namespace IntervalAut

/-- Coerce an `IntervalAut` to its underlying function `[0,1] → [0,1]`. -/
instance : CoeFun IntervalAut (fun _ ↦ IntervalPoint → IntervalPoint) where
  coe f := f.toHomeomorph

/-- Extensionality for interval automorphisms. -/
@[ext]
theorem ext (f g : IntervalAut) (h : ∀ x, f x = g x) : f = g := by
  cases f
  cases g
  congr 1
  exact DFunLike.ext _ _ h

/-- Coerce a positive slope unit to a real number. -/
abbrev slopeToReal (h : PositiveSlopeGroup) : ℝ :=
  ((h : NNReal) : ℝ)

/-- The identity interval automorphism. -/
def one : IntervalAut :=
  ⟨Homeomorph.refl IntervalPoint, strictMono_id⟩

/-- Composition of interval automorphisms (written multiplicatively:
`(f * g)(x) = g(f(x))`). -/
def mul (f g : IntervalAut) : IntervalAut :=
  ⟨f.toHomeomorph.trans g.toHomeomorph, g.strictMono.comp f.strictMono⟩

/-- The inverse of an interval automorphism. -/
def inv (f : IntervalAut) : IntervalAut :=
  ⟨f.toHomeomorph.symm, by
    have hmono : Monotone f.toHomeomorph.symm := by
      intro x y hxy
      have hxy' : f (f.toHomeomorph.symm x) ≤ f (f.toHomeomorph.symm y) := by simpa using hxy
      exact f.strictMono.le_iff_le.mp hxy'
    exact hmono.strictMono_of_injective f.toHomeomorph.symm.injective⟩

/-- The group structure on `IntervalAut`: composition of increasing autohomeomorphisms
of `[0,1]`, with identity `IntervalAut.one` and inverse `IntervalAut.inv`. -/
instance : Group IntervalAut where
  one := one
  mul := mul
  inv := inv
  mul_assoc _ _ _ := ext _ _ fun _ ↦ rfl
  one_mul f :=
    ext _ _ fun x ↦ by
      show (mul one f) x = f x
      simp [one, mul]
  mul_one f :=
    ext _ _ fun x ↦ by
      show (mul f one) x = f x
      simp [one, mul]
  inv_mul_cancel f :=
    ext _ _ fun x ↦ by
      show (mul (inv f) f) x = one x
      simp [mul, inv, one]

/-- The identity interval automorphism acts as the identity. -/
@[simp]
theorem one_apply (x : IntervalPoint) : ((1 : IntervalAut) x) = x :=
  rfl

/-- Multiplication of interval automorphisms is composition (in the order
`(f * g) x = g (f x)`). -/
@[simp]
theorem mul_apply (f g : IntervalAut) (x : IntervalPoint) : (f * g) x = g (f x) :=
  rfl

/-- The inverse interval automorphism is a left inverse of `f`. -/
@[simp]
theorem inv_apply_apply (f : IntervalAut) (x : IntervalPoint) : f⁻¹ (f x) = x :=
  f.toHomeomorph.symm_apply_apply x

/-- The inverse interval automorphism is a right inverse of `f`. -/
@[simp]
theorem apply_inv_apply (f : IntervalAut) (x : IntervalPoint) : f (f⁻¹ x) = x :=
  f.toHomeomorph.apply_symm_apply x

/-- Every increasing autohomeomorphism of `[0,1]` fixes `0`. -/
@[simp]
theorem map_zero (f : IntervalAut) : f 0 = 0 := by
  refine le_antisymm ?_ bot_le
  simpa using f.strictMono.monotone (bot_le (a := f.toHomeomorph.symm 0))

/-- Every increasing autohomeomorphism of `[0,1]` fixes `1`. -/
@[simp]
theorem map_one (f : IntervalAut) : f 1 = 1 := by
  refine le_antisymm le_top ?_
  simpa using f.strictMono.monotone (le_top (a := f.toHomeomorph.symm 1))

end IntervalAut

open IntervalAut

/-! ### Dlab elements and the Dlab group -/

/-- A Dlab element is *locally right `H`-linear*: on each right neighborhood, the map is
affine with slope in `H`. -/
def IsLocallyRightHLinear (H : Subgroup PositiveSlopeGroup) (f : IntervalAut) : Prop :=
  ∀ a : IntervalPoint, a < 1 →
    ∃ ε : ℝ, 0 < ε ∧ ∃ h : H, ∀ ⦃x : IntervalPoint⦄,
      (a : ℝ) < x → (x : ℝ) < (a : ℝ) + ε →
        (f x : ℝ) = (f a : ℝ) + slopeToReal h.1 * ((x : ℝ) - (a : ℝ))

/-- `f` is the identity on some neighborhood of `0`. -/
def IsIdentityNearZero (f : IntervalAut) : Prop :=
  ∃ s : Set IntervalPoint, s ∈ 𝓝 (0 : IntervalPoint) ∧ Set.EqOn f id s

/-- `f` is the identity on some neighborhood of `1`. -/
def IsIdentityNearOne (f : IntervalAut) : Prop :=
  ∃ s : Set IntervalPoint, s ∈ 𝓝 (1 : IntervalPoint) ∧ Set.EqOn f id s

/-- An interval automorphism is a *Dlab element* if it is locally right `H`-linear and
agrees with the identity near both endpoints. -/
def IsDlabElement (H : Subgroup PositiveSlopeGroup) (f : IntervalAut) : Prop :=
  IsLocallyRightHLinear H f ∧ IsIdentityNearZero f ∧ IsIdentityNearOne f

/-- The identity is always a Dlab element. -/
lemma isDlabElement_one (H : Subgroup PositiveSlopeGroup) : IsDlabElement H (1 : IntervalAut) := by
  refine
    ⟨?_, ⟨Set.univ, Filter.univ_mem, fun _ _ ↦ rfl⟩, ⟨Set.univ, Filter.univ_mem, fun _ _ ↦ rfl⟩⟩
  intro a ha
  refine ⟨1, zero_lt_one, 1, fun _ _ ↦ ?_⟩
  norm_num [slopeToReal]

/-- Composition of Dlab elements preserves local right `H`-linearity. -/
lemma isLocallyRightHLinear_mul {H : Subgroup PositiveSlopeGroup} {f g : IntervalAut}
    (hf : IsLocallyRightHLinear H f) (hg : IsLocallyRightHLinear H g) :
    IsLocallyRightHLinear H (f * g) := by
  intro a ha
  obtain ⟨ε₁, hε₁, h₁, hh₁⟩ := hf a ha
  obtain ⟨ε₂, hε₂, h₂, hh₂⟩ := hg (f a) (lt_of_lt_of_le (f.strictMono ha) (by norm_num))
  have h₁_pos : 0 < slopeToReal h₁ := by
    unfold slopeToReal
    aesop
  refine ⟨min ε₁ (ε₂ / slopeToReal h₁), lt_min hε₁ (div_pos hε₂ h₁_pos), h₂ * h₁, ?_⟩
  intro x hx₁ hx₂
  have hf_eq := hh₁ hx₁ (by linarith [min_le_left ε₁ (ε₂ / slopeToReal h₁)])
  have hfg : (f a : ℝ) < f x := f.strictMono hx₁
  have h₁_ne : slopeToReal h₁ ≠ 0 := ne_of_gt h₁_pos
  have hg_eq :=
    hh₂ hfg (by nlinarith [min_le_right ε₁ (ε₂ / slopeToReal h₁), mul_div_cancel₀ ε₂ h₁_ne])
  simp_all +decide only [Subtype.coe_lt_coe, slopeToReal, Subtype.forall, Set.mem_Icc,
    forall_and_index, NNReal.coe_pos, Units.zero_lt, lt_add_iff_pos_right,
    mul_pos_iff_of_pos_left, sub_pos, ne_eq, NNReal.coe_eq_zero, Units.ne_zero,
    not_false_eq_true, add_sub_cancel_left, mul_apply, Subgroup.coe_mul, Units.val_mul,
    NNReal.coe_mul, add_right_inj]
  ring

/-- The product of two Dlab elements is again a Dlab element. -/
lemma isDlabElement_mul {H : Subgroup PositiveSlopeGroup} {f g : IntervalAut}
    (hf : IsDlabElement H f) (hg : IsDlabElement H g) : IsDlabElement H (f * g) := by
  refine ⟨isLocallyRightHLinear_mul hf.1 hg.1, ?_, ?_⟩
  · obtain ⟨s, hs, hsEq⟩ := hg.2.1
    obtain ⟨t, ht, htEq⟩ := hf.2.1
    refine ⟨s ∩ t, Filter.inter_mem hs ht, fun x hx ↦ ?_⟩
    have hsx := hsEq hx.1
    have htx := htEq hx.2
    aesop
  · obtain ⟨s, hs, hsEq⟩ := hg.2.2
    obtain ⟨t, ht, htEq⟩ := hf.2.2
    refine ⟨s ∩ t, Filter.inter_mem hs ht, fun x hx ↦ ?_⟩
    have hsx := hsEq hx.1
    have htx := htEq hx.2
    aesop

/-- Local right `H`-linearity is preserved by inversion. -/
lemma isLocallyRightHLinear_inv {H : Subgroup PositiveSlopeGroup} {f : IntervalAut}
    (hf : IsLocallyRightHLinear H f) : IsLocallyRightHLinear H f⁻¹ := by
  intro a ha
  obtain ⟨ε, hε_pos, hε⟩ :=
    hf (f⁻¹.toHomeomorph a)
      (lt_of_le_of_ne (f⁻¹.toHomeomorph a |>.2.2) fun h ↦ by
        have h' : f⁻¹.toHomeomorph a = f⁻¹.toHomeomorph 1 := by aesop
        refine ha.ne <| ?_
        simpa using f⁻¹.toHomeomorph.injective h')
  obtain ⟨hε', hε'_pos, hε'_eq⟩ :
      ∃ ε' > 0, ∀ x : IntervalPoint,
        (a : ℝ) < x → (x : ℝ) < (a : ℝ) + ε' → (f⁻¹ x : ℝ) < (f⁻¹ a : ℝ) + ε := by
    have hcont : Continuous fun x : IntervalPoint ↦ (f⁻¹.toHomeomorph x : ℝ) := by continuity
    obtain ⟨δ, hδ_pos, hδ⟩ := Metric.continuous_iff.mp hcont a ε hε_pos
    refine ⟨δ, hδ_pos, fun x hx₁ hx₂ ↦ ?_⟩
    linarith [abs_lt.mp
        (hδ x <| by
          rw [dist_comm]
          refine abs_lt.mpr ⟨?_, ?_⟩
          · linarith [show (x : ℝ) ≥ 0 from x.2.1]
          · linarith [show (x : ℝ) ≤ 1 from x.2.2])]
  refine ⟨hε', hε'_pos, hε.choose⁻¹, ?_⟩
  intro x hx₁ hx₂
  have hx' : (f⁻¹.toHomeomorph x : ℝ) > f⁻¹.toHomeomorph a :=
    f.strictMono.lt_iff_lt.mp (by simpa using hx₁)
  have hfx := hε.choose_spec hx' (hε'_eq x hx₁ hx₂)
  simp_all +decide [slopeToReal]

/-- Identity near `0` is preserved by inversion. -/
lemma isIdentityNearZero_inv {f : IntervalAut} (hf : IsIdentityNearZero f) :
    IsIdentityNearZero f⁻¹ := by
  obtain ⟨s, hs, hsEq⟩ := hf
  refine ⟨f.toHomeomorph '' s, ?_, ?_⟩
  · rw [mem_nhds_iff] at *
    grind
  · intro x hx
    rcases hx with ⟨y, hy, rfl⟩
    simpa [hsEq hy] using inv_apply_apply f y

/-- Identity near `1` is preserved by inversion. -/
lemma isIdentityNearOne_inv {f : IntervalAut} (hf : IsIdentityNearOne f) :
    IsIdentityNearOne f⁻¹ := by
  obtain ⟨s, hs, hsEq⟩ := hf
  refine ⟨f '' s, ?_, ?_⟩
  · rw [mem_nhds_iff] at *
    grind
  · intro x hx
    rcases hx with ⟨y, hy, rfl⟩
    simpa [hsEq hy] using f.toHomeomorph.symm_apply_apply y

/-- The inverse of a Dlab element is again a Dlab element. -/
lemma isDlabElement_inv {H : Subgroup PositiveSlopeGroup} {f : IntervalAut}
    (hf : IsDlabElement H f) : IsDlabElement H f⁻¹ :=
  ⟨isLocallyRightHLinear_inv hf.1, isIdentityNearZero_inv hf.2.1, isIdentityNearOne_inv hf.2.2⟩

/-- The subgroup of interval automorphisms satisfying Dlab's defining conditions. -/
def dlabSubgroup (H : Subgroup PositiveSlopeGroup) : Subgroup IntervalAut where
  carrier := {f | IsDlabElement H f}
  one_mem' := isDlabElement_one H
  mul_mem' := isDlabElement_mul
  inv_mem' := isDlabElement_inv

/-- Dlab's group `G_H`, packaged as a group type. -/
abbrev DlabGroup (H : Subgroup PositiveSlopeGroup) : Type :=
  ↥(dlabSubgroup H)

/-- The Dlab group `DlabGroup H` inherits its group structure from `dlabSubgroup H`. -/
instance (H : Subgroup PositiveSlopeGroup) : Group (DlabGroup H) :=
  inferInstance

/-! ### Witness subgroup -/

/-- The slope subgroup used in the witness: the rank-one group `⟨2⟩`. -/
noncomputable def witnessH : Subgroup PositiveSlopeGroup :=
  rankOneSlopeGroup

/-! ### PL homeomorphism helpers

We construct PL (piecewise-linear) homeomorphisms of `[0,1]` by specifying their
real-valued formulas and verifying the necessary properties (range, inverse, continuity,
monotonicity).
-/

/-- Build an `IntervalAut` from a pair of inverse monotone functions on `ℝ` whose
restrictions to `[0,1]` give a homeomorphism. -/
noncomputable def mkIntervalAut (fR : ℝ → ℝ) (gR : ℝ → ℝ)
    (hf_maps : ∀ x, x ∈ Set.Icc 0 1 → fR x ∈ Set.Icc 0 1)
    (hg_maps : ∀ y, y ∈ Set.Icc 0 1 → gR y ∈ Set.Icc 0 1)
    (hfg : ∀ x, x ∈ Set.Icc 0 1 → gR (fR x) = x) (hgf : ∀ y, y ∈ Set.Icc 0 1 → fR (gR y) = y)
    (hcont : Continuous (fun x : IntervalPoint ↦ (⟨fR x, hf_maps x x.2⟩ : IntervalPoint)))
    (hmono : StrictMonoOn fR (Set.Icc 0 1)) : IntervalAut where
  toHomeomorph :=
    Continuous.homeoOfEquivCompactToT2 (f :=
      { toFun := fun x ↦ ⟨fR x, hf_maps x x.2⟩
        invFun := fun y ↦ ⟨gR y, hg_maps y y.2⟩
        left_inv := fun x ↦ Subtype.ext (hfg x x.2)
        right_inv := fun y ↦ Subtype.ext (hgf y y.2) }) hcont
  strictMono := fun a b hab ↦ hmono a.2 b.2 hab

/-! ### Conjugating element and test element

The *conjugating element* `conjAut` is a PL homeomorphism with slope `2` on `[0, 1/3]` and
slope `1/2` on `[1/3, 1]`. The *bump element* `bumpAut` is a PL homeomorphism that is the
identity near both endpoints but differs from the identity on the interior.
-/

/-- The real-valued formula for the conjugating PL homeomorphism. -/
noncomputable def conjReal (x : ℝ) : ℝ :=
  if x ≤ 1 / 3 then 2 * x else 2 / 3 + (x - 1 / 3) / 2

/-- The real-valued formula for the inverse of the conjugating PL homeomorphism. -/
noncomputable def conjRealInv (y : ℝ) : ℝ :=
  if y ≤ 2 / 3 then y / 2 else 1 / 3 + 2 * (y - 2 / 3)

/-- The conjugating PL formula `conjReal` maps `[0,1]` into itself. -/
lemma conjReal_maps : ∀ x, x ∈ Set.Icc 0 1 → conjReal x ∈ Set.Icc 0 1 := by
  intro x ⟨h0, h1⟩
  simp only [conjReal]
  split_ifs <;> exact ⟨by nlinarith, by nlinarith⟩

/-- The inverse formula `conjRealInv` maps `[0,1]` into itself. -/
lemma conjRealInv_maps : ∀ y, y ∈ Set.Icc 0 1 → conjRealInv y ∈ Set.Icc 0 1 := by
  intro y ⟨h0, h1⟩
  simp only [conjRealInv]
  split_ifs <;> exact ⟨by nlinarith, by nlinarith⟩

/-- `conjRealInv` is a left inverse of `conjReal` on `[0,1]`. -/
lemma conjRealInv_conjReal : ∀ x, x ∈ Set.Icc 0 1 → conjRealInv (conjReal x) = x := by
  intro x ⟨h0, h1⟩
  simp only [conjReal, conjRealInv]
  split_ifs <;> nlinarith

/-- `conjRealInv` is a right inverse of `conjReal` on `[0,1]`. -/
lemma conjReal_conjRealInv : ∀ y, y ∈ Set.Icc 0 1 → conjReal (conjRealInv y) = y := by
  intro y ⟨h0, h1⟩
  simp only [conjReal, conjRealInv]
  split_ifs <;> nlinarith

/-- The subtype-valued version of `conjReal` is continuous on `[0,1]`. -/
lemma conjReal_cont :
    Continuous (fun x : IntervalPoint ↦ (⟨conjReal x, conjReal_maps x x.2⟩ : IntervalPoint)) := by
  apply Continuous.subtype_mk
  apply_rules [Continuous.if_le, continuous_const, continuous_mul_left] <;> norm_num
  · fun_prop
  · fun_prop
  · exact continuous_subtype_val
  · intros
    subst_vars
    norm_num

/-- `conjReal` is strictly monotone on `[0,1]`. -/
lemma conjReal_strictMono : StrictMonoOn conjReal (Set.Icc 0 1) := by
  intro a ⟨ha0, ha1⟩ b ⟨hb0, hb1⟩ hab
  simp only [conjReal]
  split_ifs <;> nlinarith

/-- The conjugating PL homeomorphism: slope `2` on `[0, 1/3]`,
slope `1/2` on `[1/3, 1]`. -/
noncomputable def conjAut : IntervalAut :=
  mkIntervalAut conjReal conjRealInv conjReal_maps conjRealInv_maps conjRealInv_conjReal
    conjReal_conjRealInv conjReal_cont conjReal_strictMono

/-- The real-valued formula for the bump automorphism used to witness
non-innerness. -/
noncomputable def bumpReal (x : ℝ) : ℝ :=
  if x ≤ 1 / 4 then x
  else
    if x ≤ 3 / 8 then 1 / 4 + 2 * (x - 1 / 4)
    else if x ≤ 5 / 8 then 1 / 2 + (x - 3 / 8) / 2 else x

/-- The real-valued formula for the inverse of the bump automorphism. -/
noncomputable def bumpRealInv (y : ℝ) : ℝ :=
  if y ≤ 1 / 4 then y
  else
    if y ≤ 1 / 2 then 1 / 4 + (y - 1 / 4) / 2
    else if y ≤ 5 / 8 then 3 / 8 + 2 * (y - 1 / 2) else y

/-- The bump PL formula `bumpReal` maps `[0,1]` into itself. -/
lemma bumpReal_maps : ∀ x, x ∈ Set.Icc 0 1 → bumpReal x ∈ Set.Icc 0 1 := by
  intro x ⟨h0, h1⟩
  simp only [bumpReal]
  split_ifs <;> exact ⟨by nlinarith, by nlinarith⟩

/-- The inverse formula `bumpRealInv` maps `[0,1]` into itself. -/
lemma bumpRealInv_maps : ∀ y, y ∈ Set.Icc 0 1 → bumpRealInv y ∈ Set.Icc 0 1 := by
  intro y ⟨h0, h1⟩
  simp only [bumpRealInv]
  split_ifs <;> exact ⟨by nlinarith, by nlinarith⟩

/-- `bumpRealInv` is a left inverse of `bumpReal` on `[0,1]`. -/
lemma bumpRealInv_bumpReal : ∀ x, x ∈ Set.Icc 0 1 → bumpRealInv (bumpReal x) = x := by
  intro x ⟨h0, h1⟩
  simp only [bumpReal, bumpRealInv]
  split_ifs <;> nlinarith

/-- `bumpRealInv` is a right inverse of `bumpReal` on `[0,1]`. -/
lemma bumpReal_bumpRealInv : ∀ y, y ∈ Set.Icc 0 1 → bumpReal (bumpRealInv y) = y := by
  intro y ⟨h0, h1⟩
  simp only [bumpReal, bumpRealInv]
  split_ifs <;> nlinarith

/-- The subtype-valued version of `bumpReal` is continuous on `[0,1]`. -/
lemma bumpReal_cont :
    Continuous (fun x : IntervalPoint ↦ (⟨bumpReal x, bumpReal_maps x x.2⟩ : IntervalPoint)) := by
  refine Continuous.subtype_mk ?_ ?_
  apply_rules [Continuous.if_le, continuous_const, continuous_id] <;> norm_num
  any_goals continuity
  · intros
    subst_vars
    norm_num
  · intros
    subst_vars
    norm_num
  · intros
    subst_vars
    norm_num

/-- `bumpReal` is strictly monotone on `[0,1]`. -/
lemma bumpReal_strictMono : StrictMonoOn bumpReal (Set.Icc 0 1) := by
  intro a ⟨ha0, ha1⟩ b ⟨hb0, hb1⟩ hab
  simp only [bumpReal]
  split_ifs <;> nlinarith

/-- Non-trivial PL homeomorphism in `DlabGroup ⟨2⟩`, used as a test element for
non-innerness. -/
noncomputable def bumpAut : IntervalAut :=
  mkIntervalAut bumpReal bumpRealInv bumpReal_maps bumpRealInv_maps bumpRealInv_bumpReal
    bumpReal_bumpRealInv bumpReal_cont bumpReal_strictMono

set_option maxHeartbeats 800000 in
/-- The bump automorphism satisfies all Dlab conditions for `H = ⟨2⟩`. -/
lemma bumpAut_isDlab : IsDlabElement witnessH bumpAut := by
  constructor
  · intro a ha
    by_cases ha1 : a.val < 1 / 4
    · refine ⟨(1 / 4 - a.val) / 2, by linarith, ⟨1, witnessH.one_mem⟩, ?_⟩
      intro x hx₁ hx₂
      erw [show bumpAut.toHomeomorph x = ⟨bumpReal (x : ℝ), bumpReal_maps (x : ℝ) x.2⟩ from rfl,
        show bumpAut.toHomeomorph a = ⟨bumpReal (a : ℝ), bumpReal_maps (a : ℝ) a.2⟩ from rfl]
      norm_num [slopeToReal]
      unfold bumpReal
      split_ifs <;> nlinarith [show (x : ℝ) < 1 / 4 by linarith]
    · by_cases ha2 : a.val < 3 / 8
      · refine ⟨3 / 8 - a.val, by linarith,
            ⟨twoSlope, by simpa [witnessH] using twoSlope_mem_rankOne⟩, ?_⟩
        intro x hx₁ hx₂
        erw [show bumpAut.toHomeomorph x = ⟨bumpReal (x : ℝ), bumpReal_maps (x : ℝ) x.2⟩ from
            rfl,
          show bumpAut.toHomeomorph a = ⟨bumpReal (a : ℝ), bumpReal_maps (a : ℝ) a.2⟩ from rfl]
        norm_num [slopeToReal, twoSlope]
        unfold bumpReal
        split_ifs <;> nlinarith
      · by_cases ha3 : a.val < 5 / 8
        · refine ⟨(5 / 8 - a.val) / 2, by linarith,
              ⟨twoSlope⁻¹, by simpa [witnessH] using twoSlope_inv_mem_rankOne⟩, ?_⟩
          intro x hx₁ hx₂
          erw [show bumpAut.toHomeomorph x = ⟨bumpReal (x : ℝ), bumpReal_maps (x : ℝ) x.2⟩ from
              rfl,
            show bumpAut.toHomeomorph a = ⟨bumpReal (a : ℝ), bumpReal_maps (a : ℝ) a.2⟩ from
              rfl]
          norm_num [slopeToReal, twoSlope]
          unfold bumpReal
          split_ifs <;> nlinarith
        · refine ⟨1 - a.val, sub_pos.mpr (by simpa using ha), ⟨1, witnessH.one_mem⟩, ?_⟩
          intro x hx₁ hx₂
          erw [show bumpAut.toHomeomorph x = ⟨bumpReal (x : ℝ), bumpReal_maps (x : ℝ) x.2⟩ from
              rfl,
            show bumpAut.toHomeomorph a = ⟨bumpReal (a : ℝ), bumpReal_maps (a : ℝ) a.2⟩ from
              rfl]
          norm_num [slopeToReal]
          unfold bumpReal
          split_ifs <;> nlinarith
  · constructor
    · refine ⟨{x : IntervalPoint | x.1 ≤ 1 / 4}, ?_, ?_⟩ <;> norm_num
      · rw [Metric.mem_nhds_iff]
        norm_num [Set.subset_def, Metric.mem_ball, Subtype.dist_eq]
        refine ⟨1 / 4, ?_, fun a ha₁ ha₂ ha₃ ↦ ?_⟩
        · norm_num
        · linarith [abs_lt.mp ha₃]
      · intro x hx
        exact Subtype.ext <|
            show (bumpReal x : ℝ) = x by
              unfold bumpReal
              split_ifs <;> linarith [hx.out]
    · refine ⟨{x : IntervalPoint | x.val > 5 / 8}, ?_, ?_⟩
      · refine IsOpen.mem_nhds (isOpen_lt continuous_const continuous_subtype_val) ?_
        norm_num
      · intro x hx
        exact Subtype.ext <|
            show (bumpReal x : ℝ) = x by
              unfold bumpReal
              split_ifs <;> linarith [hx.out, x.2.1, x.2.2]

/-- The bump automorphism is not the identity. -/
lemma bumpAut_ne_one : bumpAut ≠ 1 := by
  intro h
  have h_eval :=
    congrArg (fun f ↦ f.toHomeomorph.toFun (⟨5 / 16, by norm_num⟩ : IntervalPoint)) h
  norm_num [bumpReal] at h_eval
  erw [Subtype.mk.injEq] at h_eval
  norm_num [bumpReal] at h_eval

/-! ### Local right linearity of `conjAut` and `conjAut⁻¹`

These lemmas verify that `conjAut` and its inverse are locally right `⟨2⟩`-linear, which is
needed to show that conjugation by `conjAut` preserves the Dlab subgroup.
-/

set_option maxHeartbeats 400000 in
/-- `conjAut⁻¹` is locally right `⟨2⟩`-linear. -/
lemma conjAut_inv_locallyRightHLinear : IsLocallyRightHLinear witnessH conjAut⁻¹ := by
  intro a ha
  by_cases ha' : a.val < 2 / 3
  · refine ⟨2 / 3 - a.val, ?_, ?_⟩
    · linarith
    · refine
        ⟨⟨twoSlope⁻¹, by simpa [witnessH] using twoSlope_inv_mem_rankOne⟩, fun {x} hx₁ hx₂ ↦ ?_⟩
      erw [show
          (conjAut⁻¹.toHomeomorph x : IntervalPoint) =
            ⟨conjRealInv (x : ℝ), conjRealInv_maps (x : ℝ) x.2⟩
          from rfl,
        show
          (conjAut⁻¹.toHomeomorph a : IntervalPoint) =
            ⟨conjRealInv (a : ℝ), conjRealInv_maps (a : ℝ) a.2⟩
          from rfl]
      norm_num [conjRealInv, slopeToReal, twoSlope]
      split_ifs <;> nlinarith
  · refine ⟨1 / 3, by norm_num, ?_⟩
    refine ⟨⟨twoSlope, by simpa [witnessH] using twoSlope_mem_rankOne⟩, ?_⟩
    intro x hx₁ hx₂
    change conjRealInv (x : ℝ) = conjRealInv (a : ℝ) + slopeToReal twoSlope * ((x : ℝ) - (a : ℝ))
    norm_num [slopeToReal, twoSlope, conjRealInv]
    split_ifs <;> nlinarith

set_option maxHeartbeats 400000 in
/-- `conjAut` is locally right `⟨2⟩`-linear. -/
lemma conjAut_locallyRightHLinear : IsLocallyRightHLinear witnessH conjAut := by
  intro x hx
  by_cases hx' : x.val < 1 / 3
  · refine ⟨1 / 3 - x.val, ?_, ?_⟩
    · linarith
    · refine ⟨⟨twoSlope, by simpa [witnessH] using twoSlope_mem_rankOne⟩, fun {y} hy₁ hy₂ ↦ ?_⟩
      erw [show conjAut.toHomeomorph y = ⟨conjReal (y : ℝ), conjReal_maps (y : ℝ) y.2⟩ from rfl,
        show conjAut.toHomeomorph x = ⟨conjReal (x : ℝ), conjReal_maps (x : ℝ) x.2⟩ from rfl]
      norm_num [slopeToReal, twoSlope, conjReal]
      split_ifs <;> nlinarith
  · refine ⟨1 / 3, by norm_num,
        ⟨⟨twoSlope⁻¹, by simpa [witnessH] using twoSlope_inv_mem_rankOne⟩, ?_⟩⟩
    intro a ha₁ ha₂
    erw [show conjAut.toHomeomorph a = ⟨conjReal (a : ℝ), conjReal_maps (a : ℝ) a.2⟩ from rfl,
      show conjAut.toHomeomorph x = ⟨conjReal (x : ℝ), conjReal_maps (x : ℝ) x.2⟩ from rfl]
    norm_num [slopeToReal, twoSlope, conjReal]
    split_ifs <;> nlinarith

/-- The conjugating homeomorphism lies in the ambient locally `⟨2⟩`-linear group, but
not in Dlab's compact-support subgroup: it is not the identity on any neighborhood of
`0`. -/
lemma conjAut_not_isDlabElement : ¬IsDlabElement witnessH conjAut := by
  rintro ⟨_, hzero, _⟩
  obtain ⟨s, hs, hsEq⟩ := hzero
  obtain ⟨ε, hε_pos, hε⟩ := Metric.mem_nhds_iff.mp hs
  let xval : ℝ := min (ε / 2) (1 / 6)
  have hx_pos : 0 < xval := lt_min (by linarith) (by norm_num)
  have hx_le_one : xval ≤ 1 := by
    have := min_le_right (ε / 2) (1 / 6)
    linarith
  let x : IntervalPoint := ⟨xval, ⟨le_of_lt hx_pos, hx_le_one⟩⟩
  have hx_mem : x ∈ s := by
    apply hε
    show dist x 0 < ε
    erw [Subtype.dist_eq]
    change |xval - 0| < ε
    rw [sub_zero, abs_of_nonneg (le_of_lt hx_pos)]
    have hx_le_eps : xval ≤ ε / 2 := min_le_left (ε / 2) (1 / 6)
    linarith
  have hx_fixed : (conjAut x : ℝ) = x := congrArg Subtype.val (hsEq hx_mem)
  have hx_small : xval ≤ 1 / 3 := by
    have := min_le_right (ε / 2) (1 / 6)
    linarith
  have hx_conj : (conjAut x : ℝ) = 2 * xval := by
    change conjReal xval = 2 * xval
    rw [conjReal, if_pos hx_small]
  change (conjAut x : ℝ) = xval at hx_fixed
  linarith [hx_fixed, hx_conj, hx_pos]

/-! ### The conjugation automorphism

We show that conjugation by `conjAut` preserves the Dlab subgroup `G_⟨2⟩`, and package it
as a multiplicative equivalence `conjMulEquiv`.
-/

set_option maxHeartbeats 800000 in
/-- Conjugation by `conjAut` preserves the Dlab predicate. -/
lemma isDlabElement_conj (f : IntervalAut) (hf : IsDlabElement witnessH f) :
    IsDlabElement witnessH (conjAut * f * conjAut⁻¹) := by
  constructor
  · exact isLocallyRightHLinear_mul (isLocallyRightHLinear_mul conjAut_locallyRightHLinear hf.1)
        conjAut_inv_locallyRightHLinear
  · constructor
    · obtain ⟨s, hs₁, hs₂⟩ := hf.2.1
      refine ⟨conjAut.toHomeomorph ⁻¹' s, ?_, ?_⟩
      · refine ContinuousAt.preimage_mem_nhds
            (show ContinuousAt (fun x : IntervalPoint ↦ conjAut.toHomeomorph x) 0 from
              conjAut.toHomeomorph.continuous.continuousAt)
            ?_
        simpa using hs₁
      · intro x hx
        have := hs₂ hx
        aesop
    · obtain ⟨s, hs₁, hs₂⟩ := hf.2.2
      refine ⟨conjAut.toHomeomorph.symm '' s, ?_, ?_⟩
      · rw [mem_nhds_iff] at *
        obtain ⟨t, ht₁, ht₂, ht₃⟩ := hs₁
        refine ⟨conjAut.toHomeomorph.symm '' t, ?_, conjAut.toHomeomorph.symm.isOpenMap _ ht₂, ?_⟩
        · grind
        · refine ⟨1, ht₃, ?_⟩
          unfold conjAut mkIntervalAut
          norm_num
          unfold conjReal_cont
          norm_num [Continuous.homeoOfEquivCompactToT2]
          refine Subtype.ext ?_
          unfold conjRealInv
          norm_num
      · intro x hx
        obtain ⟨y, hy, rfl⟩ := hx
        simp_all +decide only [Set.EqOn, id_eq, Subtype.forall, Set.mem_Icc, forall_and_index,
          mul_apply, Homeomorph.apply_symm_apply]
        convert congr_arg _ (hs₂ _ y.2.1 y.2.2 hy) using 1

set_option maxHeartbeats 800000 in
/-- Conjugation by `conjAut⁻¹` preserves the Dlab predicate. -/
lemma isDlabElement_conj_inv (f : IntervalAut) (hf : IsDlabElement witnessH f) :
    IsDlabElement witnessH (conjAut⁻¹ * f * conjAut) := by
  refine ⟨?_, ?_, ?_⟩
  · exact isLocallyRightHLinear_mul (isLocallyRightHLinear_mul conjAut_inv_locallyRightHLinear hf.1)
        conjAut_locallyRightHLinear
  · obtain ⟨s, hs₁, hs₂⟩ := hf.2.1
    refine ⟨conjAut⁻¹.toHomeomorph ⁻¹' s, ?_, ?_⟩
    · refine ContinuousAt.preimage_mem_nhds
          (show ContinuousAt (fun x : IntervalPoint ↦ conjAut⁻¹.toHomeomorph x) 0 from
            conjAut⁻¹.toHomeomorph.continuous.continuousAt)
          ?_
      simpa using hs₁
    · intro x hx
      aesop
  · obtain ⟨s, hs₁, hs₂⟩ := hf.2.2
    use conjAut.toHomeomorph '' s
    refine ⟨?_, ?_⟩
    · rw [mem_nhds_iff] at *
      obtain ⟨t, ht₁, ht₂, ht₃⟩ := hs₁
      refine ⟨conjAut.toHomeomorph '' t, ?_, conjAut.toHomeomorph.isOpenMap t ht₂, ?_⟩
      · grind
      · refine ⟨1, ht₃, ?_⟩
        simp [conjAut]
    · intro x hx
      rcases hx with ⟨y, hy, rfl⟩
      simp [hs₂ hy]

/-- Conjugation by `conjAut` as a group automorphism of the rank-one Dlab group. -/
noncomputable def conjMulEquiv : DlabGroup witnessH ≃* DlabGroup witnessH where
  toFun := fun ⟨f, hf⟩ ↦ ⟨conjAut * f * conjAut⁻¹, isDlabElement_conj f hf⟩
  invFun := fun ⟨f, hf⟩ ↦ ⟨conjAut⁻¹ * f * conjAut, isDlabElement_conj_inv f hf⟩
  left_inv := fun ⟨_, _⟩ ↦ Subtype.ext (by group)
  right_inv := fun ⟨_, _⟩ ↦ Subtype.ext (by group)
  map_mul' := fun ⟨f, _⟩ ⟨g, _⟩ ↦
    Subtype.ext (by
        show
          conjAut * (f * g) * conjAut⁻¹ = (conjAut * f * conjAut⁻¹) * (conjAut * g * conjAut⁻¹)
        group)

/-! ### Fixed-point analysis and non-innerness

The key technical lemma: any element fixed by `conjMulEquiv` must be the identity. This
uses an orbit-growth argument — conjugation by the PL homeomorphism `conjAut` expands the
fixed-point set of `f` from a neighborhood of `0` to all of `[0,1]`.
-/

/-- A non-identity element of the rank-one Dlab group, used to witness that
`conjMulEquiv ≠ id`. -/
noncomputable def witnessElement : DlabGroup witnessH :=
  ⟨bumpAut, bumpAut_isDlab⟩

/-- The witness element is not the identity. -/
lemma witnessElement_ne_one : witnessElement ≠ 1 := fun h ↦
  bumpAut_ne_one (congr_arg Subtype.val h)

set_option maxHeartbeats 800000 in
/-- Any element of the rank-one Dlab group that is fixed by conjugation with `conjAut`
must be the identity. The proof proceeds by showing that the fixed-point set of `f`
expands under iteration of `conjReal`, eventually covering all of `[0,1]`. -/
theorem eq_one_of_conjMulEquiv_eq_self (f : DlabGroup witnessH) (hfix : conjMulEquiv f = f) :
    f = 1 := by
  have h_eq : ∀ x : IntervalPoint, f.1 (conjAut x) = conjAut (f.1 x) := by
    intro x
    have hfix' := congrArg (fun g : DlabGroup witnessH ↦ g.1 x) hfix
    have hpoint : conjAut⁻¹ (f.1 (conjAut x)) = f.1 x := by simpa [conjMulEquiv] using hfix'
    simpa using congrArg conjAut.toHomeomorph hpoint
  obtain ⟨r, hr₀, hr₁⟩ : ∃ r : ℝ, 0 < r ∧ r < 1 ∧ ∀ x : IntervalPoint, x.val ≤ r → f.1 x = x := by
    obtain ⟨s, hs₀, hs₁⟩ := f.2.2.1
    obtain ⟨ε, εpos, hε⟩ := Metric.mem_nhds_iff.mp hs₀
    refine ⟨min (ε / 2) (1 / 2), ?_, ?_, ?_⟩ <;> norm_num [εpos]
    intro a ha₁ ha₂ ha₃ ha₄
    specialize hs₁ <|
        hε <|
          show dist ⟨a, ⟨ha₁, ha₂⟩⟩ 0 < ε by
            erw [Subtype.dist_eq]
            simpa [abs_of_nonneg ha₁] using by linarith
    aesop
  let iter : ℕ → ℝ := fun n ↦ Nat.rec r (fun _ r' ↦ conjReal r') n
  have h_ind : ∀ n : ℕ, ∀ x : IntervalPoint, x.val ≤ iter n → f.1 x = x := by
    intro n
    induction n with
    | zero => exact hr₁.2
    | succ n ih =>
      intro x hx
      have h_preimage : conjAut⁻¹ x ∈ {y : IntervalPoint | y.val ≤ iter n} := by
        have h_preimage_le : conjRealInv x.val ≤ iter n := by
          have h_conjRealInv_x_le : conjReal (conjRealInv x.val) = x.val :=
            conjReal_conjRealInv x x.2
          contrapose! hx
          simp_all +decide only [Subtype.forall, Set.mem_Icc, forall_and_index, conjReal,
            one_div, iter]
          split_ifs at * <;> linarith [show (x : ℝ) ≤ 1 from x.2.2]
        exact h_preimage_le
      have h_preimage_fixed : f.1 (conjAut⁻¹ x) = conjAut⁻¹ x := ih _ h_preimage
      have h_eq_preimage := h_eq (conjAut⁻¹.toHomeomorph x)
      simpa [h_preimage_fixed] using h_eq_preimage
  have h_lim : Filter.Tendsto iter Filter.atTop (nhds 1) := by
    have h_inc : StrictMono iter := by
      refine strictMono_nat_of_lt_succ ?_
      intro n
      refine Nat.recOn n ?_ ?_ <;> norm_num [iter, conjReal]
      · split_ifs <;> linarith
      · grind
    obtain ⟨L, hL⟩ : ∃ L, Filter.Tendsto iter Filter.atTop (nhds L) := by
      have h_bound : ∀ n, (iter n : ℝ) ≤ 1 := by
        intro n
        induction n <;> norm_num [iter, conjReal]
        · linarith
        · split_ifs <;> linarith!
      exact ⟨_,
          tendsto_atTop_isLUB h_inc.monotone
            (isLUB_ciSup ⟨1, Set.forall_mem_range.mpr h_bound⟩)⟩
    have hL_fixed : conjReal L = L := by
      have h_conj_tendsto :
        Filter.Tendsto (fun n ↦ conjReal (iter n : ℝ)) Filter.atTop (nhds (conjReal L)) := by
        refine Continuous.continuousAt ?_ |>.tendsto.comp hL
        apply_rules [Continuous.if_le, Continuous.add, Continuous.mul, continuous_id,
          continuous_const]
        norm_num
      exact tendsto_nhds_unique h_conj_tendsto (hL.comp (Filter.tendsto_add_atTop_nat 1))
    convert hL
    unfold conjReal at hL_fixed
    split_ifs at hL_fixed <;>
      linarith [show L > 0 from
          lt_of_lt_of_le hr₀
            (le_of_tendsto_of_tendsto' tendsto_const_nhds hL fun n ↦ h_inc.monotone n.zero_le)]
  have h_id : ∀ x : IntervalPoint, f.1 x = x := by
    intro x
    by_cases hx : x.val < 1
    · obtain ⟨n, hn⟩ := (h_lim.eventually (lt_mem_nhds hx)).exists
      exact h_ind n x hn.le
    · cases eq_or_lt_of_le x.2.2 <;> aesop
  exact Subtype.ext <| ext _ _ h_id

/-- The conjugation automorphism is not inner: no element `h` satisfies
`conjMulEquiv = MulAut.conj h`, because any such `h` would be fixed by `conjMulEquiv`
(hence equal to `1`), contradicting that `conjMulEquiv` moves `witnessElement`. -/
theorem conjMulEquiv_not_inner : conjMulEquiv ∉ MulAut.innerSubgroup (DlabGroup witnessH) := by
  intro ⟨h, hh⟩
  have hfixed : conjMulEquiv h = h := by
    have : (MulAut.conj h) h = h := by simp [MulAut.conj_apply]
    rw [hh] at this
    exact this
  have h1 : h = 1 := eq_one_of_conjMulEquiv_eq_self h hfixed
  have hid : ∀ x, conjMulEquiv x = x := by
    intro x
    have := congr_fun (congr_arg DFunLike.coe hh) x
    rw [h1] at this
    simp only [_root_.map_one, MulAut.one_apply] at this
    exact this.symm
  exact witnessElement_ne_one (eq_one_of_conjMulEquiv_eq_self witnessElement (hid _))

/-! ### First-disagreement linear order

We define a strict total order on the rank-one Dlab group by comparing elements at the
first point where they disagree. This order is preserved by conjugation with `conjAut`.
-/

/-- The *first-disagreement* strict relation: `f` is below `g` iff there exists a point
`x` where `f(x) < g(x)` and every point where `g(y) < f(y)` lies to the right of `x`.

For Dlab's rank-one groups this is the formal first-gradient comparison: local
right-linearity makes the sign at the first disagreement equivalent to the comparison
of the first nontrivial right slopes. -/
def FirstDisagreementLt (H : Subgroup PositiveSlopeGroup) (f g : DlabGroup H) : Prop :=
  ∃ x : IntervalPoint,
    (f.1 x : ℝ) < (g.1 x : ℝ) ∧
      ∀ y : IntervalPoint, (g.1 y : ℝ) < (f.1 y : ℝ) → (x : ℝ) < (y : ℝ)

/-- The rank-one first-disagreement relation used to build the witness order. -/
def fd_lt (f g : DlabGroup witnessH) : Prop :=
  ∃ x : IntervalPoint,
    (f.1 x : ℝ) < (g.1 x : ℝ) ∧
      ∀ y : IntervalPoint, (g.1 y : ℝ) < (f.1 y : ℝ) → (x : ℝ) < (y : ℝ)

/-- `fd_lt` is irreflexive. -/
lemma fd_lt_irrefl (f : DlabGroup witnessH) : ¬fd_lt f f := fun ⟨_, hlt, _⟩ ↦ lt_irrefl _ hlt

/-- `fd_lt` is asymmetric. -/
lemma fd_lt_asymm {f g : DlabGroup witnessH} (h : fd_lt f g) : ¬fd_lt g f := fun ⟨y, hgy, hy⟩ ↦ by
  obtain ⟨x, hfx, hx⟩ := h
  linarith [hx y hgy, hy x hfx]

/-- `fd_lt` is transitive. -/
lemma fd_lt_trans {f g h : DlabGroup witnessH} (hfg : fd_lt f g) (hgh : fd_lt g h) :
    fd_lt f h := by
  obtain ⟨x, hx₁, hx₂⟩ := hfg
  obtain ⟨y, hy₁, hy₂⟩ := hgh
  by_cases hxy : (x : ℝ) ≤ (y : ℝ) <;> grind +locals

set_option maxHeartbeats 800000 in
/-- `fd_lt` satisfies trichotomy: for any `f g`, exactly one of `f = g`, `fd_lt f g`,
or `fd_lt g f` holds. -/
lemma fd_lt_trichotomy (f g : DlabGroup witnessH) : f = g ∨ fd_lt f g ∨ fd_lt g f := by
  by_contra! h_contra
  have h_inf : ∀ x : IntervalPoint, (f.1 x : ℝ) < (g.1 x : ℝ) →
      ∃ y : IntervalPoint, (g.1 y : ℝ) < (f.1 y : ℝ) ∧ (y : ℝ) ≤ (x : ℝ) := by
    intro x hx
    exact not_not.1 fun h ↦ h_contra.2.1 ⟨x, hx, fun y hy ↦ not_le.1 fun hxy ↦ h ⟨y, hy, hxy⟩⟩
  have h_inf_rev : ∀ x : IntervalPoint, (g.1 x : ℝ) < (f.1 x : ℝ) →
      ∃ y : IntervalPoint, (f.1 y : ℝ) < (g.1 y : ℝ) ∧ (y : ℝ) ≤ (x : ℝ) := by
    intro x hx
    exact not_forall_not.mp fun h ↦
        h_contra.2.2 ⟨x, hx, fun y hy ↦ not_le.mp fun hxy ↦ h y <| by tauto⟩
  obtain ⟨L, hL⟩ :
      ∃ L : ℝ, L ∈ Set.Icc 0 1 ∧
        (∀ x : IntervalPoint, (f.1 x : ℝ) ≠ (g.1 x : ℝ) → L ≤ (x : ℝ)) ∧
        (∀ ε > 0, ∃ x : IntervalPoint, (f.1 x : ℝ) ≠ (g.1 x : ℝ) ∧ (x : ℝ) < L + ε) := by
    have h_nonempty : ∃ x : IntervalPoint, (f.1 x : ℝ) ≠ (g.1 x : ℝ) :=
      not_forall.mp fun h ↦
        h_contra.1 <|
          Subtype.ext <| by
            ext
            exact h _
    use sInf {x : ℝ | ∃ p : IntervalPoint, p.val = x ∧ (f.1 p : ℝ) ≠ (g.1 p : ℝ)}
    refine ⟨⟨?_, ?_⟩, ?_, ?_⟩
    · exact le_csInf ⟨_, ⟨h_nonempty.choose, rfl, h_nonempty.choose_spec⟩⟩ fun x hx ↦ by
          obtain ⟨p, rfl, _⟩ := hx
          exact p.2.1
    · exact le_trans
          (csInf_le
            ⟨0, by
              rintro x ⟨p, rfl, _⟩
              exact p.2.1⟩
            ⟨h_nonempty.choose, rfl, h_nonempty.choose_spec⟩)
          h_nonempty.choose.2.2
    · exact fun x hx ↦
        csInf_le
          ⟨0, by
            rintro x ⟨p, rfl, _⟩
            exact p.2.1⟩
          ⟨x, rfl, hx⟩
    · intro ε ε_pos
      have :=
        exists_lt_of_csInf_lt
          (show {x : ℝ | ∃ p : IntervalPoint, p.val = x ∧ (f.1 p : ℝ) ≠ (g.1 p : ℝ)}.Nonempty
            from ⟨_, ⟨h_nonempty.choose, rfl, h_nonempty.choose_spec⟩⟩)
          (lt_add_of_pos_right _ ε_pos)
      aesop
  have h_eq : (f.1 ⟨L, hL.left⟩ : ℝ) = (g.1 ⟨L, hL.left⟩ : ℝ) := by
    by_contra h_eq'
    obtain ⟨ε, hε_pos, hε⟩ :
      ∃ ε > 0, ∀ x : IntervalPoint, abs ((x : ℝ) - L) < ε → (f.1 x : ℝ) ≠ (g.1 x : ℝ) := by
      have h_cont : Continuous (fun x : IntervalPoint ↦ (f.1 x : ℝ) - (g.1 x : ℝ)) := by
        fun_prop
      have := Metric.continuous_iff.mp h_cont ⟨L, hL.1⟩
      exact Exists.elim
          (this (|(f.1 ⟨L, hL.1⟩ : ℝ) - (g.1 ⟨L, hL.1⟩ : ℝ)|)
            (abs_pos.mpr (sub_ne_zero.mpr h_eq')))
          fun δ hδ ↦
          ⟨δ, hδ.1, fun x hx hx' ↦
            h_eq' <| by
              cases abs_cases ((f.1 ⟨L, hL.1⟩ : ℝ) - (g.1 ⟨L, hL.1⟩ : ℝ)) <;>
                linarith [abs_lt.mp (hδ.2 x <| by simpa [Subtype.dist_eq] using hx)]⟩
    obtain ⟨x, hx₁, hx₂⟩ : ∃ x : IntervalPoint, (f.1 x : ℝ) ≠ (g.1 x : ℝ) ∧ (x : ℝ) < L := by
      by_cases hL_zero : L = 0
      · simp_all +decide
      · use ⟨max 0 (L - ε / 2),
            ⟨le_max_left _ _, max_le (by linarith [hL.1.1]) (by linarith [hL.1.2])⟩⟩
        exact ⟨hε _ <|
              abs_lt.mpr
                ⟨by cases max_cases 0 (L - ε / 2) <;> linarith [hL.1.1, hL.1.2], by
                  cases max_cases 0 (L - ε / 2) <;> linarith [hL.1.1, hL.1.2]⟩, by
            cases max_cases 0 (L - ε / 2) <;>
              linarith [hL.1.1, hL.1.2,
                show L > 0 from lt_of_le_of_ne hL.1.1 (Ne.symm hL_zero)]⟩
    linarith [hL.2.1 x hx₁]
  obtain ⟨ε, hε_pos, hε⟩ :
      ∃ ε > 0, ∃ h_f h_g : PositiveSlopeGroup, ∀ x : IntervalPoint,
        L < (x : ℝ) → (x : ℝ) < L + ε →
          (f.1 x : ℝ) = (f.1 ⟨L, hL.left⟩ : ℝ) + slopeToReal h_f * ((x : ℝ) - L) ∧
          (g.1 x : ℝ) = (g.1 ⟨L, hL.left⟩ : ℝ) + slopeToReal h_g * ((x : ℝ) - L) := by
    have h_locally_right_linear :
        ∀ f : DlabGroup witnessH, ∀ a : IntervalPoint, a < 1 →
          ∃ ε > 0, ∃ h : PositiveSlopeGroup, ∀ x : IntervalPoint,
            (a : ℝ) < x → (x : ℝ) < (a : ℝ) + ε →
              (f.1 x : ℝ) = (f.1 a : ℝ) + slopeToReal h * ((x : ℝ) - (a : ℝ)) := by
      intro f a ha
      have := f.2.1 a ha
      exact ⟨this.choose, this.choose_spec.1, this.choose_spec.2.choose.1,
          this.choose_spec.2.choose_spec⟩
    by_cases hL1 : L = 1
    · use 1
      norm_num [hL1]
      exact ⟨1, 1, by
          intros
          linarith⟩
    · obtain ⟨ε_f, hε_f_pos, hε_f⟩ :=
        h_locally_right_linear f ⟨L, hL.left⟩ (Subtype.mk_lt_mk.mpr (lt_of_le_of_ne hL.1.2 hL1))
      obtain ⟨ε_g, hε_g_pos, hε_g⟩ :=
        h_locally_right_linear g ⟨L, hL.left⟩ (Subtype.mk_lt_mk.mpr (lt_of_le_of_ne hL.1.2 hL1))
      exact ⟨min ε_f ε_g, lt_min hε_f_pos hε_g_pos, hε_f.choose, hε_g.choose, fun x hx₁ hx₂ ↦
          ⟨hε_f.choose_spec x hx₁ (by linarith [min_le_left ε_f ε_g]),
            hε_g.choose_spec x hx₁ (by linarith [min_le_right ε_f ε_g])⟩⟩
  obtain ⟨h_f, h_g, hε⟩ := hε
  have h_neq : h_f ≠ h_g := by
    intro h_eq_hg
    have h_eq_fg :
      ∀ x : IntervalPoint, L < (x : ℝ) → (x : ℝ) < L + ε → (f.1 x : ℝ) = (g.1 x : ℝ) := by grind
    obtain ⟨x, hx₁, hx₂⟩ := hL.2.2 ε hε_pos
    by_cases hx₃ : L < (x : ℝ)
    · exact hx₁ <| h_eq_fg x hx₃ hx₂
    · exact hx₁ <| by
          rw [show x = ⟨L, hL.1⟩ from
              Subtype.ext <| le_antisymm (le_of_not_gt hx₃) (hL.2.1 x hx₁)]
          exact h_eq
  by_cases h_cases : slopeToReal h_f < slopeToReal h_g
  · have h_lt :
      ∀ x : IntervalPoint, L < (x : ℝ) → (x : ℝ) < L + ε → (f.1 x : ℝ) < (g.1 x : ℝ) :=
      fun x hx₁ hx₂ ↦ by nlinarith [hε x hx₁ hx₂]
    obtain ⟨x, hx⟩ :
      ∃ x : IntervalPoint, L < (x : ℝ) ∧ (x : ℝ) < L + ε ∧ (f.1 x : ℝ) < (g.1 x : ℝ) := by
      obtain ⟨x, hx₁, hx₂⟩ := hL.2.2 ε hε_pos
      grind
    obtain ⟨y, hy₁, hy₂⟩ := h_inf x hx.2.2
    grind
  · have h_gt : slopeToReal h_f > slopeToReal h_g :=
      lt_of_le_of_ne (le_of_not_gt h_cases) (Ne.symm <| by simpa [Units.ext_iff] using h_neq)
    obtain ⟨x, hx₁, hx₂⟩ :
      ∃ x : IntervalPoint, L < (x : ℝ) ∧ (x : ℝ) < L + ε ∧ (g.1 x : ℝ) < (f.1 x : ℝ) := by
      obtain ⟨x, hx₁, hx₂⟩ : ∃ x : ℝ, L < x ∧ x < L + ε ∧ x ∈ Set.Icc 0 1 := by
        by_cases hL1 : L = 1
        · obtain ⟨x, hx₁, hx₂⟩ := hL.2.2 1 zero_lt_one
          have := hL.2.1 x hx₁
          norm_num [hL1] at this
          exact False.elim <|
              hx₁ <| by
                rw [show x = ⟨1, by norm_num⟩ from
                    Subtype.ext <| le_antisymm (by linarith [x.2.2]) this]
                simp [map_one]
        · by_cases hL2 : L + ε > 1
          · exact ⟨1, lt_of_le_of_ne hL.1.2 hL1, hL2, by norm_num⟩
          · exact ⟨L + ε / 2, by linarith, by linarith,
                ⟨by linarith [hL.1.1], by linarith [hL.1.2]⟩⟩
      exact ⟨⟨x, hx₂.2⟩, hx₁, hx₂.1, by nlinarith [hε ⟨x, hx₂.2⟩ hx₁ hx₂.1]⟩
    obtain ⟨y, hy₁, hy₂⟩ := h_inf_rev x hx₂.2
    have := hL.2.1 y (by linarith)
    by_cases hy₃ : y.val = L
    · grind
    · have := hε y (lt_of_le_of_ne this (Ne.symm hy₃)) (by linarith)
      nlinarith [show (y : ℝ) > L from lt_of_le_of_ne ‹_› (Ne.symm hy₃)]

/-! ### Order-preservation of conjugation -/

/-- Evaluate the conjugation equivalence pointwise on `[0,1]`. -/
lemma conjMulEquiv_val_apply (f : DlabGroup witnessH) (x : IntervalPoint) :
    (conjMulEquiv f).1 x = conjAut⁻¹ (f.1 (conjAut x)) :=
  rfl

/-- The first-disagreement order is preserved by `conjMulEquiv`. -/
lemma fd_lt_conj_iff (f g : DlabGroup witnessH) :
    fd_lt f g ↔ fd_lt (conjMulEquiv f) (conjMulEquiv g) := by
  constructor <;> rintro ⟨x, hx₁, hx₂⟩
  · refine ⟨conjAut⁻¹ x, ?_, ?_⟩
    · convert StrictMono.lt_iff_lt
            (show StrictMono (fun y : IntervalPoint ↦ conjAut⁻¹ y) from ?_) |>.2
          hx₁ using 1
      · simp [conjMulEquiv_val_apply]
      · convert inv (conjAut : IntervalAut) |>.strictMono using 1
    · intro y hy
      have h_conj : (g.1 (conjAut y) : ℝ) < (f.1 (conjAut y) : ℝ) :=
        conjAut⁻¹.strictMono.lt_iff_lt.mp hy
      contrapose! hx₂
      refine ⟨conjAut y, h_conj, le_trans (conjAut.strictMono.monotone hx₂) ?_⟩
      simp [conjAut]
  · refine ⟨conjAut x, ?_, ?_⟩
    · contrapose! hx₁
      exact conjAut⁻¹.strictMono.monotone hx₁
    · intro y hy
      contrapose! hx₂
      refine ⟨conjAut⁻¹ y, ?_, ?_⟩ <;> simp_all +decide [conjMulEquiv_val_apply]
      · exact conjAut⁻¹.strictMono hy
      · refine le_trans (conjAut⁻¹.strictMono.monotone hx₂) ?_
        simp

/-- The first-disagreement strict order is left-translation invariant: if `fd_lt f g`,
then `fd_lt (c * f) (c * g)`. -/
lemma fd_lt_mul_left (c f g : DlabGroup witnessH) (hfg : fd_lt f g) : fd_lt (c * f) (c * g) := by
  obtain ⟨x, hx₁, hx₂⟩ := hfg
  refine ⟨c.1⁻¹ x, ?_, ?_⟩
  · simpa using hx₁
  · intro y hy
    have hy' : (g.1 (c.1 y) : ℝ) < (f.1 (c.1 y) : ℝ) := by simpa using hy
    have hxcy : (x : ℝ) < (c.1 y : ℝ) := hx₂ (c.1 y) hy'
    have := c.1⁻¹.strictMono hxcy
    simpa using this

/-- Left-translation invariance of `fd_lt` as an `iff`: `fd_lt f g ↔ fd_lt (c * f) (c * g)`. -/
lemma fd_lt_mul_left_iff (c f g : DlabGroup witnessH) : fd_lt f g ↔ fd_lt (c * f) (c * g) := by
  constructor
  · exact fd_lt_mul_left c f g
  · intro h
    simpa [mul_assoc] using fd_lt_mul_left c⁻¹ (c * f) (c * g) h

/-- The first-disagreement strict order is right-translation invariant: if `fd_lt f g`,
then `fd_lt (f * c) (g * c)`. -/
lemma fd_lt_mul_right (c f g : DlabGroup witnessH) (hfg : fd_lt f g) : fd_lt (f * c) (g * c) := by
  obtain ⟨x, hx₁, hx₂⟩ := hfg
  refine ⟨x, ?_, ?_⟩
  · simpa using c.1.strictMono hx₁
  · intro y hy
    have hy' : (g.1 y : ℝ) < (f.1 y : ℝ) := c.1.strictMono.lt_iff_lt.mp (by simpa using hy)
    exact hx₂ y hy'

/-- Right-translation invariance of `fd_lt` as an `iff`: `fd_lt f g ↔ fd_lt (f * c) (g * c)`. -/
lemma fd_lt_mul_right_iff (c f g : DlabGroup witnessH) : fd_lt f g ↔ fd_lt (f * c) (g * c) := by
  constructor
  · exact fd_lt_mul_right c f g
  · intro h
    have h' := fd_lt_mul_right c⁻¹ (f * c) (g * c) h
    simpa [mul_assoc] using h'

/-! ### Linear order witness -/

/-- An explicit linear order on the rank-one Dlab group via first disagreement. -/
noncomputable def witnessLinearOrder : LinearOrder (DlabGroup witnessH) := by
  have : Std.Trichotomous (r := fd_lt) :=
    ⟨fun a b h1 h2 ↦ by
      rcases fd_lt_trichotomy a b with rfl | h | h
      · rfl
      · exact absurd h h1
      · exact absurd h h2⟩
  have : Std.Irrefl (α := DlabGroup witnessH) fd_lt := ⟨fd_lt_irrefl⟩
  have : IsTrans (DlabGroup witnessH) fd_lt := ⟨@fd_lt_trans⟩
  have : DecidableRel (α := DlabGroup witnessH) fd_lt := Classical.decRel _
  have : IsStrictTotalOrder (DlabGroup witnessH) fd_lt := {}
  exact linearOrderOfSTO fd_lt

noncomputable local instance : LinearOrder (DlabGroup witnessH) :=
  witnessLinearOrder

/-- The linear order agrees with `fd_lt` on `≤`. -/
lemma witnessLinearOrder_le_iff (a b : DlabGroup witnessH) :
    @LE.le _ witnessLinearOrder.toLE a b ↔ (a = b ∨ fd_lt a b) :=
  Eq.to_iff rfl

/-- The rank-one private relation is the public first-disagreement relation. -/
lemma fd_lt_iff_firstDisagreement (a b : DlabGroup witnessH) :
    fd_lt a b ↔ FirstDisagreementLt witnessH a b :=
  Iff.rfl

/-- The linear order agrees with `fd_lt` on `<`. -/
lemma witnessLinearOrder_lt_iff (a b : DlabGroup witnessH) :
    @LT.lt _ witnessLinearOrder.toLT a b ↔ fd_lt a b :=
  Eq.to_iff rfl

/-- A linear order on a group is bi-invariant if multiplication on both sides preserves
the order. -/
structure IsBiInvariantLinearOrder (G : Type*) [Group G] (o : LinearOrder G) : Prop where
  le_mul_left : ∀ a b c : G, @LE.le _ o.toLE a b → @LE.le _ o.toLE (c * a) (c * b)
  le_mul_right : ∀ a b c : G, @LE.le _ o.toLE a b → @LE.le _ o.toLE (a * c) (b * c)

/-- A Dlab bi-order is the first-disagreement Dlab order, compatible with multiplication
on both sides. -/
structure IsDlabBiOrder (H : Subgroup PositiveSlopeGroup) (o : LinearOrder (DlabGroup H)) :
    Prop extends IsBiInvariantLinearOrder (DlabGroup H) o where
  lt_iff_firstDisagreement :
    ∀ a b : DlabGroup H, @LT.lt _ o.toLT a b ↔ FirstDisagreementLt H a b

/-- The first-disagreement order is a bi-order on the rank-one Dlab group. -/
theorem witnessLinearOrder_isDlabBiOrder : IsDlabBiOrder witnessH witnessLinearOrder where
  le_mul_left := by
    intro a b c hab
    rw [witnessLinearOrder_le_iff] at hab ⊢
    rcases hab with rfl | h
    · exact Or.inl rfl
    · exact Or.inr (fd_lt_mul_left c a b h)
  le_mul_right := by
    intro a b c hab
    rw [witnessLinearOrder_le_iff] at hab ⊢
    rcases hab with rfl | h
    · exact Or.inl rfl
    · exact Or.inr (fd_lt_mul_right c a b h)
  lt_iff_firstDisagreement := by
    intro a b
    exact (witnessLinearOrder_lt_iff a b).trans (fd_lt_iff_firstDisagreement a b)

/-- The order automorphism induced by conjugation with `conjAut`. -/
noncomputable def witnessOrderAut : DlabGroup witnessH ≃*o DlabGroup witnessH :=
  { toMulEquiv := conjMulEquiv
    map_le_map_iff' := by
      intro a b
      simp only [witnessLinearOrder_le_iff]
      constructor
      · rintro (h | h)
        · exact Or.inl (conjMulEquiv.injective h)
        · exact Or.inr ((fd_lt_conj_iff a b).mpr h)
      · rintro (rfl | h)
        · exact Or.inl rfl
        · exact Or.inr ((fd_lt_conj_iff a b).mp h) }

/-- The explicit ordered Dlab witness has a non-inner order automorphism. -/
theorem witnessOrderAut_not_inner :
    witnessOrderAut.toMulEquiv ∉ MulAut.innerSubgroup (DlabGroup witnessH) :=
  conjMulEquiv_not_inner

/-- The rank-one conjugating interval automorphism. -/
noncomputable def rankOneConjAut : IntervalAut :=
  conjAut

/-- The rank-one Dlab group automorphism induced by the conjugating PL map. -/
noncomputable def rankOneConjMulEquiv :
    DlabGroup rankOneSlopeGroup ≃* DlabGroup rankOneSlopeGroup :=
  conjMulEquiv

/-- The Dlab bi-order used by the rank-one witness.

Informally, this is Dlab's natural order from Theorem 4.1 for the order inherited
by `⟨2⟩`: for `f ≠ 1`, `1 < f` exactly when the first nontrivial right slope of
`f` is greater than `1`. The formal definition below realizes this order as the
first-disagreement order on interval homeomorphisms. -/
noncomputable def rankOneDlabOrder : LinearOrder (DlabGroup rankOneSlopeGroup) :=
  witnessLinearOrder

noncomputable local instance : LinearOrder (DlabGroup rankOneSlopeGroup) :=
  rankOneDlabOrder

/-- The rank-one Dlab order is compatible with multiplication on both sides. -/
theorem rankOneDlabOrder_isDlabBiOrder : IsDlabBiOrder rankOneSlopeGroup rankOneDlabOrder :=
  witnessLinearOrder_isDlabBiOrder

/-- The order automorphism of the rank-one Dlab group induced by the conjugating PL map. -/
noncomputable def rankOneConjOrderAut :
    DlabGroup rankOneSlopeGroup ≃*o DlabGroup rankOneSlopeGroup :=
  witnessOrderAut

/-- The rank-one conjugation order automorphism is not inner. -/
theorem rankOneConjOrderAut_not_inner :
    rankOneConjOrderAut.toMulEquiv ∉ MulAut.innerSubgroup (DlabGroup rankOneSlopeGroup) :=
  witnessOrderAut_not_inner

/-! ### Kourovka 21.149 witness -/

/-- A group has a bi-invariant linear order with a non-inner order automorphism. -/
def HasNonInnerOrderAutomorphism (G : Type*) [Group G] : Prop :=
  ∃ o : LinearOrder G,
    IsBiInvariantLinearOrder G o ∧
      let _ : LinearOrder G := o
      ∃ φ : G ≃*o G, φ.toMulEquiv ∉ MulAut.innerSubgroup G

/-- The compact interval rank-one witness satisfies the generic ordered-group target. -/
theorem rankOneCompactInterval_hasOrderAutNotInner :
    HasNonInnerOrderAutomorphism (DlabGroup rankOneSlopeGroup) :=
  ⟨rankOneDlabOrder, rankOneDlabOrder_isDlabBiOrder.toIsBiInvariantLinearOrder,
    rankOneConjOrderAut, rankOneConjOrderAut_not_inner⟩

/-- **Kourovka 21.149**: there exists a Dlab group with an order automorphism that is
not inner. -/
theorem existsDlabGroupOrderAutNotInner :
    ∃ H : Subgroup PositiveSlopeGroup, ∃ o : LinearOrder (DlabGroup H),
      IsDlabBiOrder H o ∧
        let _ : LinearOrder (DlabGroup H) := o
        ∃ φ : DlabGroup H ≃*o DlabGroup H,
          φ.toMulEquiv ∉ MulAut.innerSubgroup (DlabGroup H) :=
  ⟨rankOneSlopeGroup, rankOneDlabOrder, rankOneDlabOrder_isDlabBiOrder, rankOneConjOrderAut,
    rankOneConjOrderAut_not_inner⟩

end Solution21_149
end KourovkaNotebook
