/-
Copyright (c) 2026 Pietro Monticone. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aristotle (Harmonic), Elias Judin, Pietro Monticone
-/
import Kourovka.Util.PSU33.TwoTransitive

/-!
# Root transvection surface for `PSU(3,3)`

This file defines the root-transvection surface used by the final Iwasawa and
generation arguments.
-/

namespace PSU33

open PSU33.HermitianForm
open scoped Classical

/-!
## Explicit `PSU(3,3)` root-unipotent (transvection) generators

We specialize the generic Eichler/Siegel transvection API to `K = F9`,
`σ = conj9`. Because `conj9 a = a³`, the *skew* (unitary) condition
`a + σ a = 0` becomes `a + a³ = 0`, i.e. `a` lies in the additive group of
trace-zero elements of `GF(9)` over `GF(3)` (the `3`-element "center" of the root
group). For each isotropic vector `u` and each such skew parameter `a` we obtain
an explicit root-unipotent element of `specialUnitaryGroup = SU(3,3)`.

Together with diagonal (`diagSpecialUnitary`) and permutation
(`permSpecialUnitary`) elements these transvections are the standard
structural generators of `SU(3,3)`. This file defines the root-generated subgroup
and records the closure reduction; `PSU33.RootGeneration` supplies the generation
theorem used by the final Iwasawa argument. -/

/-- An explicit **root-unipotent (transvection) element** of
`specialUnitaryGroup`: the Eichler/Siegel transvection `E_{u,a}` along an
isotropic vector `u` (`hermForm conj9 u u = 0`) with skew parameter `a`
(`a + a³ = 0`). -/
noncomputable def transvection (u : Fin 3 → F9) (hu : hermForm conj9 u u = 0)
    (a : F9) (ha : a + a ^ 3 = 0) : specialUnitaryGroup :=
  eichlerSpecialUnitary conj9_involutive u hu a ha

/-- The underlying linear map of a root-unipotent element is the transvection. -/
@[simp] lemma coe_transvection (u : Fin 3 → F9) (hu : hermForm conj9 u u = 0)
    (a : F9) (ha : a + a ^ 3 = 0) :
    ((transvection u hu a ha).1.1 : (Fin 3 → F9) ≃ₗ[F9] (Fin 3 → F9)) =
    eichlerTransvection u hu a := rfl

/-!
## The root-generated subgroup of `SU(3,3)`

We specialize the generic root-subgroup API to `PSU(3,3)` over `GF(9)`. The
`specialUnitaryGroup` (= `SU(3,3)`) contains the normal subgroup
`rootGenerated` generated by all skew Eichler/Siegel transvections, and the
geometric Iwasawa route uses the statement that this subgroup is everything
(`rootGenerated = ⊤`).
-/

/-- The root-generated subgroup of `specialUnitaryGroup` (= `SU(3,3)`): the
subgroup generated by all skew Eichler/Siegel transvections. -/
noncomputable def rootGenerated : Subgroup specialUnitaryGroup :=
  HermitianForm.rootGenerated conj9_involutive

/-- **The root-generated subgroup of `SU(3,3)` is normal.** -/
theorem rootGenerated_normal : rootGenerated.Normal :=
  HermitianForm.rootGenerated_normal conj9_involutive

/-- **Permutation generation from root generation.** If the skew transvections
generate all of `SU(3,3)` (`rootGenerated = ⊤`, equivalently
`Subgroup.closure (transvectionSet conj9_involutive) = ⊤`), then the geometric
projective unitary permutation group `psuPerm` is generated by the permutation
images of those transvections. -/
theorem psuPerm_eq_closure_transvections
    (hgen : rootGenerated = ⊤) :
    psuPerm = Subgroup.closure
    ((MulAction.toPermHom specialUnitaryGroup IsotropicPoint) ''
      transvectionSet conj9_involutive) :=
  psuPerm_eq_closure_image (transvectionSet conj9_involutive) hgen

end PSU33
